import * as _235 from "./abci/types";
import * as _236 from "./crypto/keys";
import * as _237 from "./crypto/proof";
import * as _238 from "./libs/bits/types";
import * as _239 from "./p2p/types";
import * as _240 from "./types/block";
import * as _241 from "./types/evidence";
import * as _242 from "./types/params";
import * as _243 from "./types/types";
import * as _244 from "./types/validator";
import * as _245 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _235.CheckTxType;
        checkTxTypeToJSON(object: _235.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _235.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _235.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _235.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _235.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _235.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _235.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _235.MisbehaviorType;
        misbehaviorTypeToJSON(object: _235.MisbehaviorType): string;
        CheckTxType: typeof _235.CheckTxType;
        CheckTxTypeSDKType: typeof _235.CheckTxType;
        CheckTxTypeAmino: typeof _235.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _235.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _235.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _235.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _235.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _235.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _235.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _235.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _235.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _235.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _235.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _235.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _235.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _235.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Request;
            fromPartial(object: Partial<_235.Request>): _235.Request;
            fromAmino(object: _235.RequestAmino): _235.Request;
            toAmino(message: _235.Request): _235.RequestAmino;
            fromAminoMsg(object: _235.RequestAminoMsg): _235.Request;
            fromProtoMsg(message: _235.RequestProtoMsg): _235.Request;
            toProto(message: _235.Request): Uint8Array;
            toProtoMsg(message: _235.Request): _235.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _235.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestEcho;
            fromPartial(object: Partial<_235.RequestEcho>): _235.RequestEcho;
            fromAmino(object: _235.RequestEchoAmino): _235.RequestEcho;
            toAmino(message: _235.RequestEcho): _235.RequestEchoAmino;
            fromAminoMsg(object: _235.RequestEchoAminoMsg): _235.RequestEcho;
            fromProtoMsg(message: _235.RequestEchoProtoMsg): _235.RequestEcho;
            toProto(message: _235.RequestEcho): Uint8Array;
            toProtoMsg(message: _235.RequestEcho): _235.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _235.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestFlush;
            fromPartial(_: Partial<_235.RequestFlush>): _235.RequestFlush;
            fromAmino(_: _235.RequestFlushAmino): _235.RequestFlush;
            toAmino(_: _235.RequestFlush): _235.RequestFlushAmino;
            fromAminoMsg(object: _235.RequestFlushAminoMsg): _235.RequestFlush;
            fromProtoMsg(message: _235.RequestFlushProtoMsg): _235.RequestFlush;
            toProto(message: _235.RequestFlush): Uint8Array;
            toProtoMsg(message: _235.RequestFlush): _235.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _235.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestInfo;
            fromPartial(object: Partial<_235.RequestInfo>): _235.RequestInfo;
            fromAmino(object: _235.RequestInfoAmino): _235.RequestInfo;
            toAmino(message: _235.RequestInfo): _235.RequestInfoAmino;
            fromAminoMsg(object: _235.RequestInfoAminoMsg): _235.RequestInfo;
            fromProtoMsg(message: _235.RequestInfoProtoMsg): _235.RequestInfo;
            toProto(message: _235.RequestInfo): Uint8Array;
            toProtoMsg(message: _235.RequestInfo): _235.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _235.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestInitChain;
            fromPartial(object: Partial<_235.RequestInitChain>): _235.RequestInitChain;
            fromAmino(object: _235.RequestInitChainAmino): _235.RequestInitChain;
            toAmino(message: _235.RequestInitChain): _235.RequestInitChainAmino;
            fromAminoMsg(object: _235.RequestInitChainAminoMsg): _235.RequestInitChain;
            fromProtoMsg(message: _235.RequestInitChainProtoMsg): _235.RequestInitChain;
            toProto(message: _235.RequestInitChain): Uint8Array;
            toProtoMsg(message: _235.RequestInitChain): _235.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _235.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestQuery;
            fromPartial(object: Partial<_235.RequestQuery>): _235.RequestQuery;
            fromAmino(object: _235.RequestQueryAmino): _235.RequestQuery;
            toAmino(message: _235.RequestQuery): _235.RequestQueryAmino;
            fromAminoMsg(object: _235.RequestQueryAminoMsg): _235.RequestQuery;
            fromProtoMsg(message: _235.RequestQueryProtoMsg): _235.RequestQuery;
            toProto(message: _235.RequestQuery): Uint8Array;
            toProtoMsg(message: _235.RequestQuery): _235.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _235.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestBeginBlock;
            fromPartial(object: Partial<_235.RequestBeginBlock>): _235.RequestBeginBlock;
            fromAmino(object: _235.RequestBeginBlockAmino): _235.RequestBeginBlock;
            toAmino(message: _235.RequestBeginBlock): _235.RequestBeginBlockAmino;
            fromAminoMsg(object: _235.RequestBeginBlockAminoMsg): _235.RequestBeginBlock;
            fromProtoMsg(message: _235.RequestBeginBlockProtoMsg): _235.RequestBeginBlock;
            toProto(message: _235.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _235.RequestBeginBlock): _235.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _235.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestCheckTx;
            fromPartial(object: Partial<_235.RequestCheckTx>): _235.RequestCheckTx;
            fromAmino(object: _235.RequestCheckTxAmino): _235.RequestCheckTx;
            toAmino(message: _235.RequestCheckTx): _235.RequestCheckTxAmino;
            fromAminoMsg(object: _235.RequestCheckTxAminoMsg): _235.RequestCheckTx;
            fromProtoMsg(message: _235.RequestCheckTxProtoMsg): _235.RequestCheckTx;
            toProto(message: _235.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _235.RequestCheckTx): _235.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _235.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestDeliverTx;
            fromPartial(object: Partial<_235.RequestDeliverTx>): _235.RequestDeliverTx;
            fromAmino(object: _235.RequestDeliverTxAmino): _235.RequestDeliverTx;
            toAmino(message: _235.RequestDeliverTx): _235.RequestDeliverTxAmino;
            fromAminoMsg(object: _235.RequestDeliverTxAminoMsg): _235.RequestDeliverTx;
            fromProtoMsg(message: _235.RequestDeliverTxProtoMsg): _235.RequestDeliverTx;
            toProto(message: _235.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _235.RequestDeliverTx): _235.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _235.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestEndBlock;
            fromPartial(object: Partial<_235.RequestEndBlock>): _235.RequestEndBlock;
            fromAmino(object: _235.RequestEndBlockAmino): _235.RequestEndBlock;
            toAmino(message: _235.RequestEndBlock): _235.RequestEndBlockAmino;
            fromAminoMsg(object: _235.RequestEndBlockAminoMsg): _235.RequestEndBlock;
            fromProtoMsg(message: _235.RequestEndBlockProtoMsg): _235.RequestEndBlock;
            toProto(message: _235.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _235.RequestEndBlock): _235.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _235.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestCommit;
            fromPartial(_: Partial<_235.RequestCommit>): _235.RequestCommit;
            fromAmino(_: _235.RequestCommitAmino): _235.RequestCommit;
            toAmino(_: _235.RequestCommit): _235.RequestCommitAmino;
            fromAminoMsg(object: _235.RequestCommitAminoMsg): _235.RequestCommit;
            fromProtoMsg(message: _235.RequestCommitProtoMsg): _235.RequestCommit;
            toProto(message: _235.RequestCommit): Uint8Array;
            toProtoMsg(message: _235.RequestCommit): _235.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _235.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestListSnapshots;
            fromPartial(_: Partial<_235.RequestListSnapshots>): _235.RequestListSnapshots;
            fromAmino(_: _235.RequestListSnapshotsAmino): _235.RequestListSnapshots;
            toAmino(_: _235.RequestListSnapshots): _235.RequestListSnapshotsAmino;
            fromAminoMsg(object: _235.RequestListSnapshotsAminoMsg): _235.RequestListSnapshots;
            fromProtoMsg(message: _235.RequestListSnapshotsProtoMsg): _235.RequestListSnapshots;
            toProto(message: _235.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _235.RequestListSnapshots): _235.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _235.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestOfferSnapshot;
            fromPartial(object: Partial<_235.RequestOfferSnapshot>): _235.RequestOfferSnapshot;
            fromAmino(object: _235.RequestOfferSnapshotAmino): _235.RequestOfferSnapshot;
            toAmino(message: _235.RequestOfferSnapshot): _235.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _235.RequestOfferSnapshotAminoMsg): _235.RequestOfferSnapshot;
            fromProtoMsg(message: _235.RequestOfferSnapshotProtoMsg): _235.RequestOfferSnapshot;
            toProto(message: _235.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _235.RequestOfferSnapshot): _235.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _235.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_235.RequestLoadSnapshotChunk>): _235.RequestLoadSnapshotChunk;
            fromAmino(object: _235.RequestLoadSnapshotChunkAmino): _235.RequestLoadSnapshotChunk;
            toAmino(message: _235.RequestLoadSnapshotChunk): _235.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _235.RequestLoadSnapshotChunkAminoMsg): _235.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _235.RequestLoadSnapshotChunkProtoMsg): _235.RequestLoadSnapshotChunk;
            toProto(message: _235.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _235.RequestLoadSnapshotChunk): _235.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _235.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_235.RequestApplySnapshotChunk>): _235.RequestApplySnapshotChunk;
            fromAmino(object: _235.RequestApplySnapshotChunkAmino): _235.RequestApplySnapshotChunk;
            toAmino(message: _235.RequestApplySnapshotChunk): _235.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _235.RequestApplySnapshotChunkAminoMsg): _235.RequestApplySnapshotChunk;
            fromProtoMsg(message: _235.RequestApplySnapshotChunkProtoMsg): _235.RequestApplySnapshotChunk;
            toProto(message: _235.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _235.RequestApplySnapshotChunk): _235.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _235.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestPrepareProposal;
            fromPartial(object: Partial<_235.RequestPrepareProposal>): _235.RequestPrepareProposal;
            fromAmino(object: _235.RequestPrepareProposalAmino): _235.RequestPrepareProposal;
            toAmino(message: _235.RequestPrepareProposal): _235.RequestPrepareProposalAmino;
            fromAminoMsg(object: _235.RequestPrepareProposalAminoMsg): _235.RequestPrepareProposal;
            fromProtoMsg(message: _235.RequestPrepareProposalProtoMsg): _235.RequestPrepareProposal;
            toProto(message: _235.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _235.RequestPrepareProposal): _235.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _235.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.RequestProcessProposal;
            fromPartial(object: Partial<_235.RequestProcessProposal>): _235.RequestProcessProposal;
            fromAmino(object: _235.RequestProcessProposalAmino): _235.RequestProcessProposal;
            toAmino(message: _235.RequestProcessProposal): _235.RequestProcessProposalAmino;
            fromAminoMsg(object: _235.RequestProcessProposalAminoMsg): _235.RequestProcessProposal;
            fromProtoMsg(message: _235.RequestProcessProposalProtoMsg): _235.RequestProcessProposal;
            toProto(message: _235.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _235.RequestProcessProposal): _235.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _235.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Response;
            fromPartial(object: Partial<_235.Response>): _235.Response;
            fromAmino(object: _235.ResponseAmino): _235.Response;
            toAmino(message: _235.Response): _235.ResponseAmino;
            fromAminoMsg(object: _235.ResponseAminoMsg): _235.Response;
            fromProtoMsg(message: _235.ResponseProtoMsg): _235.Response;
            toProto(message: _235.Response): Uint8Array;
            toProtoMsg(message: _235.Response): _235.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _235.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseException;
            fromPartial(object: Partial<_235.ResponseException>): _235.ResponseException;
            fromAmino(object: _235.ResponseExceptionAmino): _235.ResponseException;
            toAmino(message: _235.ResponseException): _235.ResponseExceptionAmino;
            fromAminoMsg(object: _235.ResponseExceptionAminoMsg): _235.ResponseException;
            fromProtoMsg(message: _235.ResponseExceptionProtoMsg): _235.ResponseException;
            toProto(message: _235.ResponseException): Uint8Array;
            toProtoMsg(message: _235.ResponseException): _235.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _235.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseEcho;
            fromPartial(object: Partial<_235.ResponseEcho>): _235.ResponseEcho;
            fromAmino(object: _235.ResponseEchoAmino): _235.ResponseEcho;
            toAmino(message: _235.ResponseEcho): _235.ResponseEchoAmino;
            fromAminoMsg(object: _235.ResponseEchoAminoMsg): _235.ResponseEcho;
            fromProtoMsg(message: _235.ResponseEchoProtoMsg): _235.ResponseEcho;
            toProto(message: _235.ResponseEcho): Uint8Array;
            toProtoMsg(message: _235.ResponseEcho): _235.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _235.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseFlush;
            fromPartial(_: Partial<_235.ResponseFlush>): _235.ResponseFlush;
            fromAmino(_: _235.ResponseFlushAmino): _235.ResponseFlush;
            toAmino(_: _235.ResponseFlush): _235.ResponseFlushAmino;
            fromAminoMsg(object: _235.ResponseFlushAminoMsg): _235.ResponseFlush;
            fromProtoMsg(message: _235.ResponseFlushProtoMsg): _235.ResponseFlush;
            toProto(message: _235.ResponseFlush): Uint8Array;
            toProtoMsg(message: _235.ResponseFlush): _235.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _235.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseInfo;
            fromPartial(object: Partial<_235.ResponseInfo>): _235.ResponseInfo;
            fromAmino(object: _235.ResponseInfoAmino): _235.ResponseInfo;
            toAmino(message: _235.ResponseInfo): _235.ResponseInfoAmino;
            fromAminoMsg(object: _235.ResponseInfoAminoMsg): _235.ResponseInfo;
            fromProtoMsg(message: _235.ResponseInfoProtoMsg): _235.ResponseInfo;
            toProto(message: _235.ResponseInfo): Uint8Array;
            toProtoMsg(message: _235.ResponseInfo): _235.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _235.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseInitChain;
            fromPartial(object: Partial<_235.ResponseInitChain>): _235.ResponseInitChain;
            fromAmino(object: _235.ResponseInitChainAmino): _235.ResponseInitChain;
            toAmino(message: _235.ResponseInitChain): _235.ResponseInitChainAmino;
            fromAminoMsg(object: _235.ResponseInitChainAminoMsg): _235.ResponseInitChain;
            fromProtoMsg(message: _235.ResponseInitChainProtoMsg): _235.ResponseInitChain;
            toProto(message: _235.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _235.ResponseInitChain): _235.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _235.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseQuery;
            fromPartial(object: Partial<_235.ResponseQuery>): _235.ResponseQuery;
            fromAmino(object: _235.ResponseQueryAmino): _235.ResponseQuery;
            toAmino(message: _235.ResponseQuery): _235.ResponseQueryAmino;
            fromAminoMsg(object: _235.ResponseQueryAminoMsg): _235.ResponseQuery;
            fromProtoMsg(message: _235.ResponseQueryProtoMsg): _235.ResponseQuery;
            toProto(message: _235.ResponseQuery): Uint8Array;
            toProtoMsg(message: _235.ResponseQuery): _235.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _235.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseBeginBlock;
            fromPartial(object: Partial<_235.ResponseBeginBlock>): _235.ResponseBeginBlock;
            fromAmino(object: _235.ResponseBeginBlockAmino): _235.ResponseBeginBlock;
            toAmino(message: _235.ResponseBeginBlock): _235.ResponseBeginBlockAmino;
            fromAminoMsg(object: _235.ResponseBeginBlockAminoMsg): _235.ResponseBeginBlock;
            fromProtoMsg(message: _235.ResponseBeginBlockProtoMsg): _235.ResponseBeginBlock;
            toProto(message: _235.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _235.ResponseBeginBlock): _235.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _235.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseCheckTx;
            fromPartial(object: Partial<_235.ResponseCheckTx>): _235.ResponseCheckTx;
            fromAmino(object: _235.ResponseCheckTxAmino): _235.ResponseCheckTx;
            toAmino(message: _235.ResponseCheckTx): _235.ResponseCheckTxAmino;
            fromAminoMsg(object: _235.ResponseCheckTxAminoMsg): _235.ResponseCheckTx;
            fromProtoMsg(message: _235.ResponseCheckTxProtoMsg): _235.ResponseCheckTx;
            toProto(message: _235.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _235.ResponseCheckTx): _235.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _235.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseDeliverTx;
            fromPartial(object: Partial<_235.ResponseDeliverTx>): _235.ResponseDeliverTx;
            fromAmino(object: _235.ResponseDeliverTxAmino): _235.ResponseDeliverTx;
            toAmino(message: _235.ResponseDeliverTx): _235.ResponseDeliverTxAmino;
            fromAminoMsg(object: _235.ResponseDeliverTxAminoMsg): _235.ResponseDeliverTx;
            fromProtoMsg(message: _235.ResponseDeliverTxProtoMsg): _235.ResponseDeliverTx;
            toProto(message: _235.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _235.ResponseDeliverTx): _235.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _235.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseEndBlock;
            fromPartial(object: Partial<_235.ResponseEndBlock>): _235.ResponseEndBlock;
            fromAmino(object: _235.ResponseEndBlockAmino): _235.ResponseEndBlock;
            toAmino(message: _235.ResponseEndBlock): _235.ResponseEndBlockAmino;
            fromAminoMsg(object: _235.ResponseEndBlockAminoMsg): _235.ResponseEndBlock;
            fromProtoMsg(message: _235.ResponseEndBlockProtoMsg): _235.ResponseEndBlock;
            toProto(message: _235.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _235.ResponseEndBlock): _235.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _235.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseCommit;
            fromPartial(object: Partial<_235.ResponseCommit>): _235.ResponseCommit;
            fromAmino(object: _235.ResponseCommitAmino): _235.ResponseCommit;
            toAmino(message: _235.ResponseCommit): _235.ResponseCommitAmino;
            fromAminoMsg(object: _235.ResponseCommitAminoMsg): _235.ResponseCommit;
            fromProtoMsg(message: _235.ResponseCommitProtoMsg): _235.ResponseCommit;
            toProto(message: _235.ResponseCommit): Uint8Array;
            toProtoMsg(message: _235.ResponseCommit): _235.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _235.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseListSnapshots;
            fromPartial(object: Partial<_235.ResponseListSnapshots>): _235.ResponseListSnapshots;
            fromAmino(object: _235.ResponseListSnapshotsAmino): _235.ResponseListSnapshots;
            toAmino(message: _235.ResponseListSnapshots): _235.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _235.ResponseListSnapshotsAminoMsg): _235.ResponseListSnapshots;
            fromProtoMsg(message: _235.ResponseListSnapshotsProtoMsg): _235.ResponseListSnapshots;
            toProto(message: _235.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _235.ResponseListSnapshots): _235.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _235.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseOfferSnapshot;
            fromPartial(object: Partial<_235.ResponseOfferSnapshot>): _235.ResponseOfferSnapshot;
            fromAmino(object: _235.ResponseOfferSnapshotAmino): _235.ResponseOfferSnapshot;
            toAmino(message: _235.ResponseOfferSnapshot): _235.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _235.ResponseOfferSnapshotAminoMsg): _235.ResponseOfferSnapshot;
            fromProtoMsg(message: _235.ResponseOfferSnapshotProtoMsg): _235.ResponseOfferSnapshot;
            toProto(message: _235.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _235.ResponseOfferSnapshot): _235.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _235.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_235.ResponseLoadSnapshotChunk>): _235.ResponseLoadSnapshotChunk;
            fromAmino(object: _235.ResponseLoadSnapshotChunkAmino): _235.ResponseLoadSnapshotChunk;
            toAmino(message: _235.ResponseLoadSnapshotChunk): _235.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _235.ResponseLoadSnapshotChunkAminoMsg): _235.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _235.ResponseLoadSnapshotChunkProtoMsg): _235.ResponseLoadSnapshotChunk;
            toProto(message: _235.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _235.ResponseLoadSnapshotChunk): _235.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _235.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_235.ResponseApplySnapshotChunk>): _235.ResponseApplySnapshotChunk;
            fromAmino(object: _235.ResponseApplySnapshotChunkAmino): _235.ResponseApplySnapshotChunk;
            toAmino(message: _235.ResponseApplySnapshotChunk): _235.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _235.ResponseApplySnapshotChunkAminoMsg): _235.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _235.ResponseApplySnapshotChunkProtoMsg): _235.ResponseApplySnapshotChunk;
            toProto(message: _235.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _235.ResponseApplySnapshotChunk): _235.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _235.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponsePrepareProposal;
            fromPartial(object: Partial<_235.ResponsePrepareProposal>): _235.ResponsePrepareProposal;
            fromAmino(object: _235.ResponsePrepareProposalAmino): _235.ResponsePrepareProposal;
            toAmino(message: _235.ResponsePrepareProposal): _235.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _235.ResponsePrepareProposalAminoMsg): _235.ResponsePrepareProposal;
            fromProtoMsg(message: _235.ResponsePrepareProposalProtoMsg): _235.ResponsePrepareProposal;
            toProto(message: _235.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _235.ResponsePrepareProposal): _235.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _235.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ResponseProcessProposal;
            fromPartial(object: Partial<_235.ResponseProcessProposal>): _235.ResponseProcessProposal;
            fromAmino(object: _235.ResponseProcessProposalAmino): _235.ResponseProcessProposal;
            toAmino(message: _235.ResponseProcessProposal): _235.ResponseProcessProposalAmino;
            fromAminoMsg(object: _235.ResponseProcessProposalAminoMsg): _235.ResponseProcessProposal;
            fromProtoMsg(message: _235.ResponseProcessProposalProtoMsg): _235.ResponseProcessProposal;
            toProto(message: _235.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _235.ResponseProcessProposal): _235.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _235.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.CommitInfo;
            fromPartial(object: Partial<_235.CommitInfo>): _235.CommitInfo;
            fromAmino(object: _235.CommitInfoAmino): _235.CommitInfo;
            toAmino(message: _235.CommitInfo): _235.CommitInfoAmino;
            fromAminoMsg(object: _235.CommitInfoAminoMsg): _235.CommitInfo;
            fromProtoMsg(message: _235.CommitInfoProtoMsg): _235.CommitInfo;
            toProto(message: _235.CommitInfo): Uint8Array;
            toProtoMsg(message: _235.CommitInfo): _235.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _235.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ExtendedCommitInfo;
            fromPartial(object: Partial<_235.ExtendedCommitInfo>): _235.ExtendedCommitInfo;
            fromAmino(object: _235.ExtendedCommitInfoAmino): _235.ExtendedCommitInfo;
            toAmino(message: _235.ExtendedCommitInfo): _235.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _235.ExtendedCommitInfoAminoMsg): _235.ExtendedCommitInfo;
            fromProtoMsg(message: _235.ExtendedCommitInfoProtoMsg): _235.ExtendedCommitInfo;
            toProto(message: _235.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _235.ExtendedCommitInfo): _235.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _235.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Event;
            fromPartial(object: Partial<_235.Event>): _235.Event;
            fromAmino(object: _235.EventAmino): _235.Event;
            toAmino(message: _235.Event): _235.EventAmino;
            fromAminoMsg(object: _235.EventAminoMsg): _235.Event;
            fromProtoMsg(message: _235.EventProtoMsg): _235.Event;
            toProto(message: _235.Event): Uint8Array;
            toProtoMsg(message: _235.Event): _235.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _235.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.EventAttribute;
            fromPartial(object: Partial<_235.EventAttribute>): _235.EventAttribute;
            fromAmino(object: _235.EventAttributeAmino): _235.EventAttribute;
            toAmino(message: _235.EventAttribute): _235.EventAttributeAmino;
            fromAminoMsg(object: _235.EventAttributeAminoMsg): _235.EventAttribute;
            fromProtoMsg(message: _235.EventAttributeProtoMsg): _235.EventAttribute;
            toProto(message: _235.EventAttribute): Uint8Array;
            toProtoMsg(message: _235.EventAttribute): _235.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _235.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.TxResult;
            fromPartial(object: Partial<_235.TxResult>): _235.TxResult;
            fromAmino(object: _235.TxResultAmino): _235.TxResult;
            toAmino(message: _235.TxResult): _235.TxResultAmino;
            fromAminoMsg(object: _235.TxResultAminoMsg): _235.TxResult;
            fromProtoMsg(message: _235.TxResultProtoMsg): _235.TxResult;
            toProto(message: _235.TxResult): Uint8Array;
            toProtoMsg(message: _235.TxResult): _235.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _235.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Validator;
            fromPartial(object: Partial<_235.Validator>): _235.Validator;
            fromAmino(object: _235.ValidatorAmino): _235.Validator;
            toAmino(message: _235.Validator): _235.ValidatorAmino;
            fromAminoMsg(object: _235.ValidatorAminoMsg): _235.Validator;
            fromProtoMsg(message: _235.ValidatorProtoMsg): _235.Validator;
            toProto(message: _235.Validator): Uint8Array;
            toProtoMsg(message: _235.Validator): _235.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _235.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ValidatorUpdate;
            fromPartial(object: Partial<_235.ValidatorUpdate>): _235.ValidatorUpdate;
            fromAmino(object: _235.ValidatorUpdateAmino): _235.ValidatorUpdate;
            toAmino(message: _235.ValidatorUpdate): _235.ValidatorUpdateAmino;
            fromAminoMsg(object: _235.ValidatorUpdateAminoMsg): _235.ValidatorUpdate;
            fromProtoMsg(message: _235.ValidatorUpdateProtoMsg): _235.ValidatorUpdate;
            toProto(message: _235.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _235.ValidatorUpdate): _235.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _235.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.VoteInfo;
            fromPartial(object: Partial<_235.VoteInfo>): _235.VoteInfo;
            fromAmino(object: _235.VoteInfoAmino): _235.VoteInfo;
            toAmino(message: _235.VoteInfo): _235.VoteInfoAmino;
            fromAminoMsg(object: _235.VoteInfoAminoMsg): _235.VoteInfo;
            fromProtoMsg(message: _235.VoteInfoProtoMsg): _235.VoteInfo;
            toProto(message: _235.VoteInfo): Uint8Array;
            toProtoMsg(message: _235.VoteInfo): _235.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _235.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.ExtendedVoteInfo;
            fromPartial(object: Partial<_235.ExtendedVoteInfo>): _235.ExtendedVoteInfo;
            fromAmino(object: _235.ExtendedVoteInfoAmino): _235.ExtendedVoteInfo;
            toAmino(message: _235.ExtendedVoteInfo): _235.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _235.ExtendedVoteInfoAminoMsg): _235.ExtendedVoteInfo;
            fromProtoMsg(message: _235.ExtendedVoteInfoProtoMsg): _235.ExtendedVoteInfo;
            toProto(message: _235.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _235.ExtendedVoteInfo): _235.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _235.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Misbehavior;
            fromPartial(object: Partial<_235.Misbehavior>): _235.Misbehavior;
            fromAmino(object: _235.MisbehaviorAmino): _235.Misbehavior;
            toAmino(message: _235.Misbehavior): _235.MisbehaviorAmino;
            fromAminoMsg(object: _235.MisbehaviorAminoMsg): _235.Misbehavior;
            fromProtoMsg(message: _235.MisbehaviorProtoMsg): _235.Misbehavior;
            toProto(message: _235.Misbehavior): Uint8Array;
            toProtoMsg(message: _235.Misbehavior): _235.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _235.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _235.Snapshot;
            fromPartial(object: Partial<_235.Snapshot>): _235.Snapshot;
            fromAmino(object: _235.SnapshotAmino): _235.Snapshot;
            toAmino(message: _235.Snapshot): _235.SnapshotAmino;
            fromAminoMsg(object: _235.SnapshotAminoMsg): _235.Snapshot;
            fromProtoMsg(message: _235.SnapshotProtoMsg): _235.Snapshot;
            toProto(message: _235.Snapshot): Uint8Array;
            toProtoMsg(message: _235.Snapshot): _235.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _237.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _237.Proof;
            fromPartial(object: Partial<_237.Proof>): _237.Proof;
            fromAmino(object: _237.ProofAmino): _237.Proof;
            toAmino(message: _237.Proof): _237.ProofAmino;
            fromAminoMsg(object: _237.ProofAminoMsg): _237.Proof;
            fromProtoMsg(message: _237.ProofProtoMsg): _237.Proof;
            toProto(message: _237.Proof): Uint8Array;
            toProtoMsg(message: _237.Proof): _237.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _237.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _237.ValueOp;
            fromPartial(object: Partial<_237.ValueOp>): _237.ValueOp;
            fromAmino(object: _237.ValueOpAmino): _237.ValueOp;
            toAmino(message: _237.ValueOp): _237.ValueOpAmino;
            fromAminoMsg(object: _237.ValueOpAminoMsg): _237.ValueOp;
            fromProtoMsg(message: _237.ValueOpProtoMsg): _237.ValueOp;
            toProto(message: _237.ValueOp): Uint8Array;
            toProtoMsg(message: _237.ValueOp): _237.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _237.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _237.DominoOp;
            fromPartial(object: Partial<_237.DominoOp>): _237.DominoOp;
            fromAmino(object: _237.DominoOpAmino): _237.DominoOp;
            toAmino(message: _237.DominoOp): _237.DominoOpAmino;
            fromAminoMsg(object: _237.DominoOpAminoMsg): _237.DominoOp;
            fromProtoMsg(message: _237.DominoOpProtoMsg): _237.DominoOp;
            toProto(message: _237.DominoOp): Uint8Array;
            toProtoMsg(message: _237.DominoOp): _237.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _237.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _237.ProofOp;
            fromPartial(object: Partial<_237.ProofOp>): _237.ProofOp;
            fromAmino(object: _237.ProofOpAmino): _237.ProofOp;
            toAmino(message: _237.ProofOp): _237.ProofOpAmino;
            fromAminoMsg(object: _237.ProofOpAminoMsg): _237.ProofOp;
            fromProtoMsg(message: _237.ProofOpProtoMsg): _237.ProofOp;
            toProto(message: _237.ProofOp): Uint8Array;
            toProtoMsg(message: _237.ProofOp): _237.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _237.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _237.ProofOps;
            fromPartial(object: Partial<_237.ProofOps>): _237.ProofOps;
            fromAmino(object: _237.ProofOpsAmino): _237.ProofOps;
            toAmino(message: _237.ProofOps): _237.ProofOpsAmino;
            fromAminoMsg(object: _237.ProofOpsAminoMsg): _237.ProofOps;
            fromProtoMsg(message: _237.ProofOpsProtoMsg): _237.ProofOps;
            toProto(message: _237.ProofOps): Uint8Array;
            toProtoMsg(message: _237.ProofOps): _237.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _236.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _236.PublicKey;
            fromPartial(object: Partial<_236.PublicKey>): _236.PublicKey;
            fromAmino(object: _236.PublicKeyAmino): _236.PublicKey;
            toAmino(message: _236.PublicKey): _236.PublicKeyAmino;
            fromAminoMsg(object: _236.PublicKeyAminoMsg): _236.PublicKey;
            fromProtoMsg(message: _236.PublicKeyProtoMsg): _236.PublicKey;
            toProto(message: _236.PublicKey): Uint8Array;
            toProtoMsg(message: _236.PublicKey): _236.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _238.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: Uint8Array | import("..").BinaryReader, length?: number): _238.BitArray;
                fromPartial(object: Partial<_238.BitArray>): _238.BitArray;
                fromAmino(object: _238.BitArrayAmino): _238.BitArray;
                toAmino(message: _238.BitArray): _238.BitArrayAmino;
                fromAminoMsg(object: _238.BitArrayAminoMsg): _238.BitArray;
                fromProtoMsg(message: _238.BitArrayProtoMsg): _238.BitArray;
                toProto(message: _238.BitArray): Uint8Array;
                toProtoMsg(message: _238.BitArray): _238.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _239.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _239.NetAddress;
            fromPartial(object: Partial<_239.NetAddress>): _239.NetAddress;
            fromAmino(object: _239.NetAddressAmino): _239.NetAddress;
            toAmino(message: _239.NetAddress): _239.NetAddressAmino;
            fromAminoMsg(object: _239.NetAddressAminoMsg): _239.NetAddress;
            fromProtoMsg(message: _239.NetAddressProtoMsg): _239.NetAddress;
            toProto(message: _239.NetAddress): Uint8Array;
            toProtoMsg(message: _239.NetAddress): _239.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _239.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _239.ProtocolVersion;
            fromPartial(object: Partial<_239.ProtocolVersion>): _239.ProtocolVersion;
            fromAmino(object: _239.ProtocolVersionAmino): _239.ProtocolVersion;
            toAmino(message: _239.ProtocolVersion): _239.ProtocolVersionAmino;
            fromAminoMsg(object: _239.ProtocolVersionAminoMsg): _239.ProtocolVersion;
            fromProtoMsg(message: _239.ProtocolVersionProtoMsg): _239.ProtocolVersion;
            toProto(message: _239.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _239.ProtocolVersion): _239.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _239.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _239.DefaultNodeInfo;
            fromPartial(object: Partial<_239.DefaultNodeInfo>): _239.DefaultNodeInfo;
            fromAmino(object: _239.DefaultNodeInfoAmino): _239.DefaultNodeInfo;
            toAmino(message: _239.DefaultNodeInfo): _239.DefaultNodeInfoAmino;
            fromAminoMsg(object: _239.DefaultNodeInfoAminoMsg): _239.DefaultNodeInfo;
            fromProtoMsg(message: _239.DefaultNodeInfoProtoMsg): _239.DefaultNodeInfo;
            toProto(message: _239.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _239.DefaultNodeInfo): _239.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _239.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _239.DefaultNodeInfoOther;
            fromPartial(object: Partial<_239.DefaultNodeInfoOther>): _239.DefaultNodeInfoOther;
            fromAmino(object: _239.DefaultNodeInfoOtherAmino): _239.DefaultNodeInfoOther;
            toAmino(message: _239.DefaultNodeInfoOther): _239.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _239.DefaultNodeInfoOtherAminoMsg): _239.DefaultNodeInfoOther;
            fromProtoMsg(message: _239.DefaultNodeInfoOtherProtoMsg): _239.DefaultNodeInfoOther;
            toProto(message: _239.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _239.DefaultNodeInfoOther): _239.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _244.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _244.ValidatorSet;
            fromPartial(object: Partial<_244.ValidatorSet>): _244.ValidatorSet;
            fromAmino(object: _244.ValidatorSetAmino): _244.ValidatorSet;
            toAmino(message: _244.ValidatorSet): _244.ValidatorSetAmino;
            fromAminoMsg(object: _244.ValidatorSetAminoMsg): _244.ValidatorSet;
            fromProtoMsg(message: _244.ValidatorSetProtoMsg): _244.ValidatorSet;
            toProto(message: _244.ValidatorSet): Uint8Array;
            toProtoMsg(message: _244.ValidatorSet): _244.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _244.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _244.Validator;
            fromPartial(object: Partial<_244.Validator>): _244.Validator;
            fromAmino(object: _244.ValidatorAmino): _244.Validator;
            toAmino(message: _244.Validator): _244.ValidatorAmino;
            fromAminoMsg(object: _244.ValidatorAminoMsg): _244.Validator;
            fromProtoMsg(message: _244.ValidatorProtoMsg): _244.Validator;
            toProto(message: _244.Validator): Uint8Array;
            toProtoMsg(message: _244.Validator): _244.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _244.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _244.SimpleValidator;
            fromPartial(object: Partial<_244.SimpleValidator>): _244.SimpleValidator;
            fromAmino(object: _244.SimpleValidatorAmino): _244.SimpleValidator;
            toAmino(message: _244.SimpleValidator): _244.SimpleValidatorAmino;
            fromAminoMsg(object: _244.SimpleValidatorAminoMsg): _244.SimpleValidator;
            fromProtoMsg(message: _244.SimpleValidatorProtoMsg): _244.SimpleValidator;
            toProto(message: _244.SimpleValidator): Uint8Array;
            toProtoMsg(message: _244.SimpleValidator): _244.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _243.BlockIDFlag;
        blockIDFlagToJSON(object: _243.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _243.SignedMsgType;
        signedMsgTypeToJSON(object: _243.SignedMsgType): string;
        BlockIDFlag: typeof _243.BlockIDFlag;
        BlockIDFlagSDKType: typeof _243.BlockIDFlag;
        BlockIDFlagAmino: typeof _243.BlockIDFlag;
        SignedMsgType: typeof _243.SignedMsgType;
        SignedMsgTypeSDKType: typeof _243.SignedMsgType;
        SignedMsgTypeAmino: typeof _243.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _243.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.PartSetHeader;
            fromPartial(object: Partial<_243.PartSetHeader>): _243.PartSetHeader;
            fromAmino(object: _243.PartSetHeaderAmino): _243.PartSetHeader;
            toAmino(message: _243.PartSetHeader): _243.PartSetHeaderAmino;
            fromAminoMsg(object: _243.PartSetHeaderAminoMsg): _243.PartSetHeader;
            fromProtoMsg(message: _243.PartSetHeaderProtoMsg): _243.PartSetHeader;
            toProto(message: _243.PartSetHeader): Uint8Array;
            toProtoMsg(message: _243.PartSetHeader): _243.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _243.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Part;
            fromPartial(object: Partial<_243.Part>): _243.Part;
            fromAmino(object: _243.PartAmino): _243.Part;
            toAmino(message: _243.Part): _243.PartAmino;
            fromAminoMsg(object: _243.PartAminoMsg): _243.Part;
            fromProtoMsg(message: _243.PartProtoMsg): _243.Part;
            toProto(message: _243.Part): Uint8Array;
            toProtoMsg(message: _243.Part): _243.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _243.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.BlockID;
            fromPartial(object: Partial<_243.BlockID>): _243.BlockID;
            fromAmino(object: _243.BlockIDAmino): _243.BlockID;
            toAmino(message: _243.BlockID): _243.BlockIDAmino;
            fromAminoMsg(object: _243.BlockIDAminoMsg): _243.BlockID;
            fromProtoMsg(message: _243.BlockIDProtoMsg): _243.BlockID;
            toProto(message: _243.BlockID): Uint8Array;
            toProtoMsg(message: _243.BlockID): _243.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _243.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Header;
            fromPartial(object: Partial<_243.Header>): _243.Header;
            fromAmino(object: _243.HeaderAmino): _243.Header;
            toAmino(message: _243.Header): _243.HeaderAmino;
            fromAminoMsg(object: _243.HeaderAminoMsg): _243.Header;
            fromProtoMsg(message: _243.HeaderProtoMsg): _243.Header;
            toProto(message: _243.Header): Uint8Array;
            toProtoMsg(message: _243.Header): _243.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _243.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Data;
            fromPartial(object: Partial<_243.Data>): _243.Data;
            fromAmino(object: _243.DataAmino): _243.Data;
            toAmino(message: _243.Data): _243.DataAmino;
            fromAminoMsg(object: _243.DataAminoMsg): _243.Data;
            fromProtoMsg(message: _243.DataProtoMsg): _243.Data;
            toProto(message: _243.Data): Uint8Array;
            toProtoMsg(message: _243.Data): _243.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _243.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Vote;
            fromPartial(object: Partial<_243.Vote>): _243.Vote;
            fromAmino(object: _243.VoteAmino): _243.Vote;
            toAmino(message: _243.Vote): _243.VoteAmino;
            fromAminoMsg(object: _243.VoteAminoMsg): _243.Vote;
            fromProtoMsg(message: _243.VoteProtoMsg): _243.Vote;
            toProto(message: _243.Vote): Uint8Array;
            toProtoMsg(message: _243.Vote): _243.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _243.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Commit;
            fromPartial(object: Partial<_243.Commit>): _243.Commit;
            fromAmino(object: _243.CommitAmino): _243.Commit;
            toAmino(message: _243.Commit): _243.CommitAmino;
            fromAminoMsg(object: _243.CommitAminoMsg): _243.Commit;
            fromProtoMsg(message: _243.CommitProtoMsg): _243.Commit;
            toProto(message: _243.Commit): Uint8Array;
            toProtoMsg(message: _243.Commit): _243.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _243.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.CommitSig;
            fromPartial(object: Partial<_243.CommitSig>): _243.CommitSig;
            fromAmino(object: _243.CommitSigAmino): _243.CommitSig;
            toAmino(message: _243.CommitSig): _243.CommitSigAmino;
            fromAminoMsg(object: _243.CommitSigAminoMsg): _243.CommitSig;
            fromProtoMsg(message: _243.CommitSigProtoMsg): _243.CommitSig;
            toProto(message: _243.CommitSig): Uint8Array;
            toProtoMsg(message: _243.CommitSig): _243.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _243.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.Proposal;
            fromPartial(object: Partial<_243.Proposal>): _243.Proposal;
            fromAmino(object: _243.ProposalAmino): _243.Proposal;
            toAmino(message: _243.Proposal): _243.ProposalAmino;
            fromAminoMsg(object: _243.ProposalAminoMsg): _243.Proposal;
            fromProtoMsg(message: _243.ProposalProtoMsg): _243.Proposal;
            toProto(message: _243.Proposal): Uint8Array;
            toProtoMsg(message: _243.Proposal): _243.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _243.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.SignedHeader;
            fromPartial(object: Partial<_243.SignedHeader>): _243.SignedHeader;
            fromAmino(object: _243.SignedHeaderAmino): _243.SignedHeader;
            toAmino(message: _243.SignedHeader): _243.SignedHeaderAmino;
            fromAminoMsg(object: _243.SignedHeaderAminoMsg): _243.SignedHeader;
            fromProtoMsg(message: _243.SignedHeaderProtoMsg): _243.SignedHeader;
            toProto(message: _243.SignedHeader): Uint8Array;
            toProtoMsg(message: _243.SignedHeader): _243.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _243.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.LightBlock;
            fromPartial(object: Partial<_243.LightBlock>): _243.LightBlock;
            fromAmino(object: _243.LightBlockAmino): _243.LightBlock;
            toAmino(message: _243.LightBlock): _243.LightBlockAmino;
            fromAminoMsg(object: _243.LightBlockAminoMsg): _243.LightBlock;
            fromProtoMsg(message: _243.LightBlockProtoMsg): _243.LightBlock;
            toProto(message: _243.LightBlock): Uint8Array;
            toProtoMsg(message: _243.LightBlock): _243.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _243.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.BlockMeta;
            fromPartial(object: Partial<_243.BlockMeta>): _243.BlockMeta;
            fromAmino(object: _243.BlockMetaAmino): _243.BlockMeta;
            toAmino(message: _243.BlockMeta): _243.BlockMetaAmino;
            fromAminoMsg(object: _243.BlockMetaAminoMsg): _243.BlockMeta;
            fromProtoMsg(message: _243.BlockMetaProtoMsg): _243.BlockMeta;
            toProto(message: _243.BlockMeta): Uint8Array;
            toProtoMsg(message: _243.BlockMeta): _243.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _243.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _243.TxProof;
            fromPartial(object: Partial<_243.TxProof>): _243.TxProof;
            fromAmino(object: _243.TxProofAmino): _243.TxProof;
            toAmino(message: _243.TxProof): _243.TxProofAmino;
            fromAminoMsg(object: _243.TxProofAminoMsg): _243.TxProof;
            fromProtoMsg(message: _243.TxProofProtoMsg): _243.TxProof;
            toProto(message: _243.TxProof): Uint8Array;
            toProtoMsg(message: _243.TxProof): _243.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _242.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.ConsensusParams;
            fromPartial(object: Partial<_242.ConsensusParams>): _242.ConsensusParams;
            fromAmino(object: _242.ConsensusParamsAmino): _242.ConsensusParams;
            toAmino(message: _242.ConsensusParams): _242.ConsensusParamsAmino;
            fromAminoMsg(object: _242.ConsensusParamsAminoMsg): _242.ConsensusParams;
            fromProtoMsg(message: _242.ConsensusParamsProtoMsg): _242.ConsensusParams;
            toProto(message: _242.ConsensusParams): Uint8Array;
            toProtoMsg(message: _242.ConsensusParams): _242.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _242.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.BlockParams;
            fromPartial(object: Partial<_242.BlockParams>): _242.BlockParams;
            fromAmino(object: _242.BlockParamsAmino): _242.BlockParams;
            toAmino(message: _242.BlockParams): _242.BlockParamsAmino;
            fromAminoMsg(object: _242.BlockParamsAminoMsg): _242.BlockParams;
            fromProtoMsg(message: _242.BlockParamsProtoMsg): _242.BlockParams;
            toProto(message: _242.BlockParams): Uint8Array;
            toProtoMsg(message: _242.BlockParams): _242.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _242.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.EvidenceParams;
            fromPartial(object: Partial<_242.EvidenceParams>): _242.EvidenceParams;
            fromAmino(object: _242.EvidenceParamsAmino): _242.EvidenceParams;
            toAmino(message: _242.EvidenceParams): _242.EvidenceParamsAmino;
            fromAminoMsg(object: _242.EvidenceParamsAminoMsg): _242.EvidenceParams;
            fromProtoMsg(message: _242.EvidenceParamsProtoMsg): _242.EvidenceParams;
            toProto(message: _242.EvidenceParams): Uint8Array;
            toProtoMsg(message: _242.EvidenceParams): _242.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _242.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.ValidatorParams;
            fromPartial(object: Partial<_242.ValidatorParams>): _242.ValidatorParams;
            fromAmino(object: _242.ValidatorParamsAmino): _242.ValidatorParams;
            toAmino(message: _242.ValidatorParams): _242.ValidatorParamsAmino;
            fromAminoMsg(object: _242.ValidatorParamsAminoMsg): _242.ValidatorParams;
            fromProtoMsg(message: _242.ValidatorParamsProtoMsg): _242.ValidatorParams;
            toProto(message: _242.ValidatorParams): Uint8Array;
            toProtoMsg(message: _242.ValidatorParams): _242.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _242.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.VersionParams;
            fromPartial(object: Partial<_242.VersionParams>): _242.VersionParams;
            fromAmino(object: _242.VersionParamsAmino): _242.VersionParams;
            toAmino(message: _242.VersionParams): _242.VersionParamsAmino;
            fromAminoMsg(object: _242.VersionParamsAminoMsg): _242.VersionParams;
            fromProtoMsg(message: _242.VersionParamsProtoMsg): _242.VersionParams;
            toProto(message: _242.VersionParams): Uint8Array;
            toProtoMsg(message: _242.VersionParams): _242.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _242.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _242.HashedParams;
            fromPartial(object: Partial<_242.HashedParams>): _242.HashedParams;
            fromAmino(object: _242.HashedParamsAmino): _242.HashedParams;
            toAmino(message: _242.HashedParams): _242.HashedParamsAmino;
            fromAminoMsg(object: _242.HashedParamsAminoMsg): _242.HashedParams;
            fromProtoMsg(message: _242.HashedParamsProtoMsg): _242.HashedParams;
            toProto(message: _242.HashedParams): Uint8Array;
            toProtoMsg(message: _242.HashedParams): _242.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _241.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _241.Evidence;
            fromPartial(object: Partial<_241.Evidence>): _241.Evidence;
            fromAmino(object: _241.EvidenceAmino): _241.Evidence;
            toAmino(message: _241.Evidence): _241.EvidenceAmino;
            fromAminoMsg(object: _241.EvidenceAminoMsg): _241.Evidence;
            fromProtoMsg(message: _241.EvidenceProtoMsg): _241.Evidence;
            toProto(message: _241.Evidence): Uint8Array;
            toProtoMsg(message: _241.Evidence): _241.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _241.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _241.DuplicateVoteEvidence;
            fromPartial(object: Partial<_241.DuplicateVoteEvidence>): _241.DuplicateVoteEvidence;
            fromAmino(object: _241.DuplicateVoteEvidenceAmino): _241.DuplicateVoteEvidence;
            toAmino(message: _241.DuplicateVoteEvidence): _241.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _241.DuplicateVoteEvidenceAminoMsg): _241.DuplicateVoteEvidence;
            fromProtoMsg(message: _241.DuplicateVoteEvidenceProtoMsg): _241.DuplicateVoteEvidence;
            toProto(message: _241.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _241.DuplicateVoteEvidence): _241.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _241.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _241.LightClientAttackEvidence;
            fromPartial(object: Partial<_241.LightClientAttackEvidence>): _241.LightClientAttackEvidence;
            fromAmino(object: _241.LightClientAttackEvidenceAmino): _241.LightClientAttackEvidence;
            toAmino(message: _241.LightClientAttackEvidence): _241.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _241.LightClientAttackEvidenceAminoMsg): _241.LightClientAttackEvidence;
            fromProtoMsg(message: _241.LightClientAttackEvidenceProtoMsg): _241.LightClientAttackEvidence;
            toProto(message: _241.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _241.LightClientAttackEvidence): _241.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _241.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _241.EvidenceList;
            fromPartial(object: Partial<_241.EvidenceList>): _241.EvidenceList;
            fromAmino(object: _241.EvidenceListAmino): _241.EvidenceList;
            toAmino(message: _241.EvidenceList): _241.EvidenceListAmino;
            fromAminoMsg(object: _241.EvidenceListAminoMsg): _241.EvidenceList;
            fromProtoMsg(message: _241.EvidenceListProtoMsg): _241.EvidenceList;
            toProto(message: _241.EvidenceList): Uint8Array;
            toProtoMsg(message: _241.EvidenceList): _241.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _240.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _240.Block;
            fromPartial(object: Partial<_240.Block>): _240.Block;
            fromAmino(object: _240.BlockAmino): _240.Block;
            toAmino(message: _240.Block): _240.BlockAmino;
            fromAminoMsg(object: _240.BlockAminoMsg): _240.Block;
            fromProtoMsg(message: _240.BlockProtoMsg): _240.Block;
            toProto(message: _240.Block): Uint8Array;
            toProtoMsg(message: _240.Block): _240.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _245.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.App;
            fromPartial(object: Partial<_245.App>): _245.App;
            fromAmino(object: _245.AppAmino): _245.App;
            toAmino(message: _245.App): _245.AppAmino;
            fromAminoMsg(object: _245.AppAminoMsg): _245.App;
            fromProtoMsg(message: _245.AppProtoMsg): _245.App;
            toProto(message: _245.App): Uint8Array;
            toProtoMsg(message: _245.App): _245.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _245.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Consensus;
            fromPartial(object: Partial<_245.Consensus>): _245.Consensus;
            fromAmino(object: _245.ConsensusAmino): _245.Consensus;
            toAmino(message: _245.Consensus): _245.ConsensusAmino;
            fromAminoMsg(object: _245.ConsensusAminoMsg): _245.Consensus;
            fromProtoMsg(message: _245.ConsensusProtoMsg): _245.Consensus;
            toProto(message: _245.Consensus): Uint8Array;
            toProtoMsg(message: _245.Consensus): _245.ConsensusProtoMsg;
        };
    };
}
