import * as _245 from "./abci/types";
import * as _246 from "./crypto/keys";
import * as _247 from "./crypto/proof";
import * as _248 from "./libs/bits/types";
import * as _249 from "./p2p/types";
import * as _250 from "./types/block";
import * as _251 from "./types/evidence";
import * as _252 from "./types/params";
import * as _253 from "./types/types";
import * as _254 from "./types/validator";
import * as _255 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _245.CheckTxType;
        checkTxTypeToJSON(object: _245.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _245.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _245.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _245.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _245.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _245.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _245.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _245.MisbehaviorType;
        misbehaviorTypeToJSON(object: _245.MisbehaviorType): string;
        CheckTxType: typeof _245.CheckTxType;
        CheckTxTypeSDKType: typeof _245.CheckTxType;
        CheckTxTypeAmino: typeof _245.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _245.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _245.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _245.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _245.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _245.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _245.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _245.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _245.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _245.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _245.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _245.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _245.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _245.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Request;
            fromPartial(object: Partial<_245.Request>): _245.Request;
            fromAmino(object: _245.RequestAmino): _245.Request;
            toAmino(message: _245.Request): _245.RequestAmino;
            fromAminoMsg(object: _245.RequestAminoMsg): _245.Request;
            fromProtoMsg(message: _245.RequestProtoMsg): _245.Request;
            toProto(message: _245.Request): Uint8Array;
            toProtoMsg(message: _245.Request): _245.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _245.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestEcho;
            fromPartial(object: Partial<_245.RequestEcho>): _245.RequestEcho;
            fromAmino(object: _245.RequestEchoAmino): _245.RequestEcho;
            toAmino(message: _245.RequestEcho): _245.RequestEchoAmino;
            fromAminoMsg(object: _245.RequestEchoAminoMsg): _245.RequestEcho;
            fromProtoMsg(message: _245.RequestEchoProtoMsg): _245.RequestEcho;
            toProto(message: _245.RequestEcho): Uint8Array;
            toProtoMsg(message: _245.RequestEcho): _245.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _245.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestFlush;
            fromPartial(_: Partial<_245.RequestFlush>): _245.RequestFlush;
            fromAmino(_: _245.RequestFlushAmino): _245.RequestFlush;
            toAmino(_: _245.RequestFlush): _245.RequestFlushAmino;
            fromAminoMsg(object: _245.RequestFlushAminoMsg): _245.RequestFlush;
            fromProtoMsg(message: _245.RequestFlushProtoMsg): _245.RequestFlush;
            toProto(message: _245.RequestFlush): Uint8Array;
            toProtoMsg(message: _245.RequestFlush): _245.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _245.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestInfo;
            fromPartial(object: Partial<_245.RequestInfo>): _245.RequestInfo;
            fromAmino(object: _245.RequestInfoAmino): _245.RequestInfo;
            toAmino(message: _245.RequestInfo): _245.RequestInfoAmino;
            fromAminoMsg(object: _245.RequestInfoAminoMsg): _245.RequestInfo;
            fromProtoMsg(message: _245.RequestInfoProtoMsg): _245.RequestInfo;
            toProto(message: _245.RequestInfo): Uint8Array;
            toProtoMsg(message: _245.RequestInfo): _245.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _245.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestInitChain;
            fromPartial(object: Partial<_245.RequestInitChain>): _245.RequestInitChain;
            fromAmino(object: _245.RequestInitChainAmino): _245.RequestInitChain;
            toAmino(message: _245.RequestInitChain): _245.RequestInitChainAmino;
            fromAminoMsg(object: _245.RequestInitChainAminoMsg): _245.RequestInitChain;
            fromProtoMsg(message: _245.RequestInitChainProtoMsg): _245.RequestInitChain;
            toProto(message: _245.RequestInitChain): Uint8Array;
            toProtoMsg(message: _245.RequestInitChain): _245.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _245.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestQuery;
            fromPartial(object: Partial<_245.RequestQuery>): _245.RequestQuery;
            fromAmino(object: _245.RequestQueryAmino): _245.RequestQuery;
            toAmino(message: _245.RequestQuery): _245.RequestQueryAmino;
            fromAminoMsg(object: _245.RequestQueryAminoMsg): _245.RequestQuery;
            fromProtoMsg(message: _245.RequestQueryProtoMsg): _245.RequestQuery;
            toProto(message: _245.RequestQuery): Uint8Array;
            toProtoMsg(message: _245.RequestQuery): _245.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _245.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestBeginBlock;
            fromPartial(object: Partial<_245.RequestBeginBlock>): _245.RequestBeginBlock;
            fromAmino(object: _245.RequestBeginBlockAmino): _245.RequestBeginBlock;
            toAmino(message: _245.RequestBeginBlock): _245.RequestBeginBlockAmino;
            fromAminoMsg(object: _245.RequestBeginBlockAminoMsg): _245.RequestBeginBlock;
            fromProtoMsg(message: _245.RequestBeginBlockProtoMsg): _245.RequestBeginBlock;
            toProto(message: _245.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _245.RequestBeginBlock): _245.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _245.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestCheckTx;
            fromPartial(object: Partial<_245.RequestCheckTx>): _245.RequestCheckTx;
            fromAmino(object: _245.RequestCheckTxAmino): _245.RequestCheckTx;
            toAmino(message: _245.RequestCheckTx): _245.RequestCheckTxAmino;
            fromAminoMsg(object: _245.RequestCheckTxAminoMsg): _245.RequestCheckTx;
            fromProtoMsg(message: _245.RequestCheckTxProtoMsg): _245.RequestCheckTx;
            toProto(message: _245.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _245.RequestCheckTx): _245.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _245.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestDeliverTx;
            fromPartial(object: Partial<_245.RequestDeliverTx>): _245.RequestDeliverTx;
            fromAmino(object: _245.RequestDeliverTxAmino): _245.RequestDeliverTx;
            toAmino(message: _245.RequestDeliverTx): _245.RequestDeliverTxAmino;
            fromAminoMsg(object: _245.RequestDeliverTxAminoMsg): _245.RequestDeliverTx;
            fromProtoMsg(message: _245.RequestDeliverTxProtoMsg): _245.RequestDeliverTx;
            toProto(message: _245.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _245.RequestDeliverTx): _245.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _245.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestEndBlock;
            fromPartial(object: Partial<_245.RequestEndBlock>): _245.RequestEndBlock;
            fromAmino(object: _245.RequestEndBlockAmino): _245.RequestEndBlock;
            toAmino(message: _245.RequestEndBlock): _245.RequestEndBlockAmino;
            fromAminoMsg(object: _245.RequestEndBlockAminoMsg): _245.RequestEndBlock;
            fromProtoMsg(message: _245.RequestEndBlockProtoMsg): _245.RequestEndBlock;
            toProto(message: _245.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _245.RequestEndBlock): _245.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _245.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestCommit;
            fromPartial(_: Partial<_245.RequestCommit>): _245.RequestCommit;
            fromAmino(_: _245.RequestCommitAmino): _245.RequestCommit;
            toAmino(_: _245.RequestCommit): _245.RequestCommitAmino;
            fromAminoMsg(object: _245.RequestCommitAminoMsg): _245.RequestCommit;
            fromProtoMsg(message: _245.RequestCommitProtoMsg): _245.RequestCommit;
            toProto(message: _245.RequestCommit): Uint8Array;
            toProtoMsg(message: _245.RequestCommit): _245.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _245.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestListSnapshots;
            fromPartial(_: Partial<_245.RequestListSnapshots>): _245.RequestListSnapshots;
            fromAmino(_: _245.RequestListSnapshotsAmino): _245.RequestListSnapshots;
            toAmino(_: _245.RequestListSnapshots): _245.RequestListSnapshotsAmino;
            fromAminoMsg(object: _245.RequestListSnapshotsAminoMsg): _245.RequestListSnapshots;
            fromProtoMsg(message: _245.RequestListSnapshotsProtoMsg): _245.RequestListSnapshots;
            toProto(message: _245.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _245.RequestListSnapshots): _245.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _245.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestOfferSnapshot;
            fromPartial(object: Partial<_245.RequestOfferSnapshot>): _245.RequestOfferSnapshot;
            fromAmino(object: _245.RequestOfferSnapshotAmino): _245.RequestOfferSnapshot;
            toAmino(message: _245.RequestOfferSnapshot): _245.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _245.RequestOfferSnapshotAminoMsg): _245.RequestOfferSnapshot;
            fromProtoMsg(message: _245.RequestOfferSnapshotProtoMsg): _245.RequestOfferSnapshot;
            toProto(message: _245.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _245.RequestOfferSnapshot): _245.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _245.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_245.RequestLoadSnapshotChunk>): _245.RequestLoadSnapshotChunk;
            fromAmino(object: _245.RequestLoadSnapshotChunkAmino): _245.RequestLoadSnapshotChunk;
            toAmino(message: _245.RequestLoadSnapshotChunk): _245.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _245.RequestLoadSnapshotChunkAminoMsg): _245.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _245.RequestLoadSnapshotChunkProtoMsg): _245.RequestLoadSnapshotChunk;
            toProto(message: _245.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _245.RequestLoadSnapshotChunk): _245.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _245.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_245.RequestApplySnapshotChunk>): _245.RequestApplySnapshotChunk;
            fromAmino(object: _245.RequestApplySnapshotChunkAmino): _245.RequestApplySnapshotChunk;
            toAmino(message: _245.RequestApplySnapshotChunk): _245.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _245.RequestApplySnapshotChunkAminoMsg): _245.RequestApplySnapshotChunk;
            fromProtoMsg(message: _245.RequestApplySnapshotChunkProtoMsg): _245.RequestApplySnapshotChunk;
            toProto(message: _245.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _245.RequestApplySnapshotChunk): _245.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _245.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestPrepareProposal;
            fromPartial(object: Partial<_245.RequestPrepareProposal>): _245.RequestPrepareProposal;
            fromAmino(object: _245.RequestPrepareProposalAmino): _245.RequestPrepareProposal;
            toAmino(message: _245.RequestPrepareProposal): _245.RequestPrepareProposalAmino;
            fromAminoMsg(object: _245.RequestPrepareProposalAminoMsg): _245.RequestPrepareProposal;
            fromProtoMsg(message: _245.RequestPrepareProposalProtoMsg): _245.RequestPrepareProposal;
            toProto(message: _245.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _245.RequestPrepareProposal): _245.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _245.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.RequestProcessProposal;
            fromPartial(object: Partial<_245.RequestProcessProposal>): _245.RequestProcessProposal;
            fromAmino(object: _245.RequestProcessProposalAmino): _245.RequestProcessProposal;
            toAmino(message: _245.RequestProcessProposal): _245.RequestProcessProposalAmino;
            fromAminoMsg(object: _245.RequestProcessProposalAminoMsg): _245.RequestProcessProposal;
            fromProtoMsg(message: _245.RequestProcessProposalProtoMsg): _245.RequestProcessProposal;
            toProto(message: _245.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _245.RequestProcessProposal): _245.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _245.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Response;
            fromPartial(object: Partial<_245.Response>): _245.Response;
            fromAmino(object: _245.ResponseAmino): _245.Response;
            toAmino(message: _245.Response): _245.ResponseAmino;
            fromAminoMsg(object: _245.ResponseAminoMsg): _245.Response;
            fromProtoMsg(message: _245.ResponseProtoMsg): _245.Response;
            toProto(message: _245.Response): Uint8Array;
            toProtoMsg(message: _245.Response): _245.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _245.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseException;
            fromPartial(object: Partial<_245.ResponseException>): _245.ResponseException;
            fromAmino(object: _245.ResponseExceptionAmino): _245.ResponseException;
            toAmino(message: _245.ResponseException): _245.ResponseExceptionAmino;
            fromAminoMsg(object: _245.ResponseExceptionAminoMsg): _245.ResponseException;
            fromProtoMsg(message: _245.ResponseExceptionProtoMsg): _245.ResponseException;
            toProto(message: _245.ResponseException): Uint8Array;
            toProtoMsg(message: _245.ResponseException): _245.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _245.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseEcho;
            fromPartial(object: Partial<_245.ResponseEcho>): _245.ResponseEcho;
            fromAmino(object: _245.ResponseEchoAmino): _245.ResponseEcho;
            toAmino(message: _245.ResponseEcho): _245.ResponseEchoAmino;
            fromAminoMsg(object: _245.ResponseEchoAminoMsg): _245.ResponseEcho;
            fromProtoMsg(message: _245.ResponseEchoProtoMsg): _245.ResponseEcho;
            toProto(message: _245.ResponseEcho): Uint8Array;
            toProtoMsg(message: _245.ResponseEcho): _245.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _245.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseFlush;
            fromPartial(_: Partial<_245.ResponseFlush>): _245.ResponseFlush;
            fromAmino(_: _245.ResponseFlushAmino): _245.ResponseFlush;
            toAmino(_: _245.ResponseFlush): _245.ResponseFlushAmino;
            fromAminoMsg(object: _245.ResponseFlushAminoMsg): _245.ResponseFlush;
            fromProtoMsg(message: _245.ResponseFlushProtoMsg): _245.ResponseFlush;
            toProto(message: _245.ResponseFlush): Uint8Array;
            toProtoMsg(message: _245.ResponseFlush): _245.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _245.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseInfo;
            fromPartial(object: Partial<_245.ResponseInfo>): _245.ResponseInfo;
            fromAmino(object: _245.ResponseInfoAmino): _245.ResponseInfo;
            toAmino(message: _245.ResponseInfo): _245.ResponseInfoAmino;
            fromAminoMsg(object: _245.ResponseInfoAminoMsg): _245.ResponseInfo;
            fromProtoMsg(message: _245.ResponseInfoProtoMsg): _245.ResponseInfo;
            toProto(message: _245.ResponseInfo): Uint8Array;
            toProtoMsg(message: _245.ResponseInfo): _245.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _245.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseInitChain;
            fromPartial(object: Partial<_245.ResponseInitChain>): _245.ResponseInitChain;
            fromAmino(object: _245.ResponseInitChainAmino): _245.ResponseInitChain;
            toAmino(message: _245.ResponseInitChain): _245.ResponseInitChainAmino;
            fromAminoMsg(object: _245.ResponseInitChainAminoMsg): _245.ResponseInitChain;
            fromProtoMsg(message: _245.ResponseInitChainProtoMsg): _245.ResponseInitChain;
            toProto(message: _245.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _245.ResponseInitChain): _245.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _245.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseQuery;
            fromPartial(object: Partial<_245.ResponseQuery>): _245.ResponseQuery;
            fromAmino(object: _245.ResponseQueryAmino): _245.ResponseQuery;
            toAmino(message: _245.ResponseQuery): _245.ResponseQueryAmino;
            fromAminoMsg(object: _245.ResponseQueryAminoMsg): _245.ResponseQuery;
            fromProtoMsg(message: _245.ResponseQueryProtoMsg): _245.ResponseQuery;
            toProto(message: _245.ResponseQuery): Uint8Array;
            toProtoMsg(message: _245.ResponseQuery): _245.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _245.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseBeginBlock;
            fromPartial(object: Partial<_245.ResponseBeginBlock>): _245.ResponseBeginBlock;
            fromAmino(object: _245.ResponseBeginBlockAmino): _245.ResponseBeginBlock;
            toAmino(message: _245.ResponseBeginBlock): _245.ResponseBeginBlockAmino;
            fromAminoMsg(object: _245.ResponseBeginBlockAminoMsg): _245.ResponseBeginBlock;
            fromProtoMsg(message: _245.ResponseBeginBlockProtoMsg): _245.ResponseBeginBlock;
            toProto(message: _245.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _245.ResponseBeginBlock): _245.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _245.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseCheckTx;
            fromPartial(object: Partial<_245.ResponseCheckTx>): _245.ResponseCheckTx;
            fromAmino(object: _245.ResponseCheckTxAmino): _245.ResponseCheckTx;
            toAmino(message: _245.ResponseCheckTx): _245.ResponseCheckTxAmino;
            fromAminoMsg(object: _245.ResponseCheckTxAminoMsg): _245.ResponseCheckTx;
            fromProtoMsg(message: _245.ResponseCheckTxProtoMsg): _245.ResponseCheckTx;
            toProto(message: _245.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _245.ResponseCheckTx): _245.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _245.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseDeliverTx;
            fromPartial(object: Partial<_245.ResponseDeliverTx>): _245.ResponseDeliverTx;
            fromAmino(object: _245.ResponseDeliverTxAmino): _245.ResponseDeliverTx;
            toAmino(message: _245.ResponseDeliverTx): _245.ResponseDeliverTxAmino;
            fromAminoMsg(object: _245.ResponseDeliverTxAminoMsg): _245.ResponseDeliverTx;
            fromProtoMsg(message: _245.ResponseDeliverTxProtoMsg): _245.ResponseDeliverTx;
            toProto(message: _245.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _245.ResponseDeliverTx): _245.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _245.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseEndBlock;
            fromPartial(object: Partial<_245.ResponseEndBlock>): _245.ResponseEndBlock;
            fromAmino(object: _245.ResponseEndBlockAmino): _245.ResponseEndBlock;
            toAmino(message: _245.ResponseEndBlock): _245.ResponseEndBlockAmino;
            fromAminoMsg(object: _245.ResponseEndBlockAminoMsg): _245.ResponseEndBlock;
            fromProtoMsg(message: _245.ResponseEndBlockProtoMsg): _245.ResponseEndBlock;
            toProto(message: _245.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _245.ResponseEndBlock): _245.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _245.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseCommit;
            fromPartial(object: Partial<_245.ResponseCommit>): _245.ResponseCommit;
            fromAmino(object: _245.ResponseCommitAmino): _245.ResponseCommit;
            toAmino(message: _245.ResponseCommit): _245.ResponseCommitAmino;
            fromAminoMsg(object: _245.ResponseCommitAminoMsg): _245.ResponseCommit;
            fromProtoMsg(message: _245.ResponseCommitProtoMsg): _245.ResponseCommit;
            toProto(message: _245.ResponseCommit): Uint8Array;
            toProtoMsg(message: _245.ResponseCommit): _245.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _245.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseListSnapshots;
            fromPartial(object: Partial<_245.ResponseListSnapshots>): _245.ResponseListSnapshots;
            fromAmino(object: _245.ResponseListSnapshotsAmino): _245.ResponseListSnapshots;
            toAmino(message: _245.ResponseListSnapshots): _245.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _245.ResponseListSnapshotsAminoMsg): _245.ResponseListSnapshots;
            fromProtoMsg(message: _245.ResponseListSnapshotsProtoMsg): _245.ResponseListSnapshots;
            toProto(message: _245.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _245.ResponseListSnapshots): _245.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _245.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseOfferSnapshot;
            fromPartial(object: Partial<_245.ResponseOfferSnapshot>): _245.ResponseOfferSnapshot;
            fromAmino(object: _245.ResponseOfferSnapshotAmino): _245.ResponseOfferSnapshot;
            toAmino(message: _245.ResponseOfferSnapshot): _245.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _245.ResponseOfferSnapshotAminoMsg): _245.ResponseOfferSnapshot;
            fromProtoMsg(message: _245.ResponseOfferSnapshotProtoMsg): _245.ResponseOfferSnapshot;
            toProto(message: _245.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _245.ResponseOfferSnapshot): _245.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _245.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_245.ResponseLoadSnapshotChunk>): _245.ResponseLoadSnapshotChunk;
            fromAmino(object: _245.ResponseLoadSnapshotChunkAmino): _245.ResponseLoadSnapshotChunk;
            toAmino(message: _245.ResponseLoadSnapshotChunk): _245.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _245.ResponseLoadSnapshotChunkAminoMsg): _245.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _245.ResponseLoadSnapshotChunkProtoMsg): _245.ResponseLoadSnapshotChunk;
            toProto(message: _245.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _245.ResponseLoadSnapshotChunk): _245.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _245.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_245.ResponseApplySnapshotChunk>): _245.ResponseApplySnapshotChunk;
            fromAmino(object: _245.ResponseApplySnapshotChunkAmino): _245.ResponseApplySnapshotChunk;
            toAmino(message: _245.ResponseApplySnapshotChunk): _245.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _245.ResponseApplySnapshotChunkAminoMsg): _245.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _245.ResponseApplySnapshotChunkProtoMsg): _245.ResponseApplySnapshotChunk;
            toProto(message: _245.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _245.ResponseApplySnapshotChunk): _245.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _245.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponsePrepareProposal;
            fromPartial(object: Partial<_245.ResponsePrepareProposal>): _245.ResponsePrepareProposal;
            fromAmino(object: _245.ResponsePrepareProposalAmino): _245.ResponsePrepareProposal;
            toAmino(message: _245.ResponsePrepareProposal): _245.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _245.ResponsePrepareProposalAminoMsg): _245.ResponsePrepareProposal;
            fromProtoMsg(message: _245.ResponsePrepareProposalProtoMsg): _245.ResponsePrepareProposal;
            toProto(message: _245.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _245.ResponsePrepareProposal): _245.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _245.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ResponseProcessProposal;
            fromPartial(object: Partial<_245.ResponseProcessProposal>): _245.ResponseProcessProposal;
            fromAmino(object: _245.ResponseProcessProposalAmino): _245.ResponseProcessProposal;
            toAmino(message: _245.ResponseProcessProposal): _245.ResponseProcessProposalAmino;
            fromAminoMsg(object: _245.ResponseProcessProposalAminoMsg): _245.ResponseProcessProposal;
            fromProtoMsg(message: _245.ResponseProcessProposalProtoMsg): _245.ResponseProcessProposal;
            toProto(message: _245.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _245.ResponseProcessProposal): _245.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _245.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.CommitInfo;
            fromPartial(object: Partial<_245.CommitInfo>): _245.CommitInfo;
            fromAmino(object: _245.CommitInfoAmino): _245.CommitInfo;
            toAmino(message: _245.CommitInfo): _245.CommitInfoAmino;
            fromAminoMsg(object: _245.CommitInfoAminoMsg): _245.CommitInfo;
            fromProtoMsg(message: _245.CommitInfoProtoMsg): _245.CommitInfo;
            toProto(message: _245.CommitInfo): Uint8Array;
            toProtoMsg(message: _245.CommitInfo): _245.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _245.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ExtendedCommitInfo;
            fromPartial(object: Partial<_245.ExtendedCommitInfo>): _245.ExtendedCommitInfo;
            fromAmino(object: _245.ExtendedCommitInfoAmino): _245.ExtendedCommitInfo;
            toAmino(message: _245.ExtendedCommitInfo): _245.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _245.ExtendedCommitInfoAminoMsg): _245.ExtendedCommitInfo;
            fromProtoMsg(message: _245.ExtendedCommitInfoProtoMsg): _245.ExtendedCommitInfo;
            toProto(message: _245.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _245.ExtendedCommitInfo): _245.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _245.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Event;
            fromPartial(object: Partial<_245.Event>): _245.Event;
            fromAmino(object: _245.EventAmino): _245.Event;
            toAmino(message: _245.Event): _245.EventAmino;
            fromAminoMsg(object: _245.EventAminoMsg): _245.Event;
            fromProtoMsg(message: _245.EventProtoMsg): _245.Event;
            toProto(message: _245.Event): Uint8Array;
            toProtoMsg(message: _245.Event): _245.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _245.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.EventAttribute;
            fromPartial(object: Partial<_245.EventAttribute>): _245.EventAttribute;
            fromAmino(object: _245.EventAttributeAmino): _245.EventAttribute;
            toAmino(message: _245.EventAttribute): _245.EventAttributeAmino;
            fromAminoMsg(object: _245.EventAttributeAminoMsg): _245.EventAttribute;
            fromProtoMsg(message: _245.EventAttributeProtoMsg): _245.EventAttribute;
            toProto(message: _245.EventAttribute): Uint8Array;
            toProtoMsg(message: _245.EventAttribute): _245.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _245.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.TxResult;
            fromPartial(object: Partial<_245.TxResult>): _245.TxResult;
            fromAmino(object: _245.TxResultAmino): _245.TxResult;
            toAmino(message: _245.TxResult): _245.TxResultAmino;
            fromAminoMsg(object: _245.TxResultAminoMsg): _245.TxResult;
            fromProtoMsg(message: _245.TxResultProtoMsg): _245.TxResult;
            toProto(message: _245.TxResult): Uint8Array;
            toProtoMsg(message: _245.TxResult): _245.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _245.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Validator;
            fromPartial(object: Partial<_245.Validator>): _245.Validator;
            fromAmino(object: _245.ValidatorAmino): _245.Validator;
            toAmino(message: _245.Validator): _245.ValidatorAmino;
            fromAminoMsg(object: _245.ValidatorAminoMsg): _245.Validator;
            fromProtoMsg(message: _245.ValidatorProtoMsg): _245.Validator;
            toProto(message: _245.Validator): Uint8Array;
            toProtoMsg(message: _245.Validator): _245.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _245.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ValidatorUpdate;
            fromPartial(object: Partial<_245.ValidatorUpdate>): _245.ValidatorUpdate;
            fromAmino(object: _245.ValidatorUpdateAmino): _245.ValidatorUpdate;
            toAmino(message: _245.ValidatorUpdate): _245.ValidatorUpdateAmino;
            fromAminoMsg(object: _245.ValidatorUpdateAminoMsg): _245.ValidatorUpdate;
            fromProtoMsg(message: _245.ValidatorUpdateProtoMsg): _245.ValidatorUpdate;
            toProto(message: _245.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _245.ValidatorUpdate): _245.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _245.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.VoteInfo;
            fromPartial(object: Partial<_245.VoteInfo>): _245.VoteInfo;
            fromAmino(object: _245.VoteInfoAmino): _245.VoteInfo;
            toAmino(message: _245.VoteInfo): _245.VoteInfoAmino;
            fromAminoMsg(object: _245.VoteInfoAminoMsg): _245.VoteInfo;
            fromProtoMsg(message: _245.VoteInfoProtoMsg): _245.VoteInfo;
            toProto(message: _245.VoteInfo): Uint8Array;
            toProtoMsg(message: _245.VoteInfo): _245.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _245.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.ExtendedVoteInfo;
            fromPartial(object: Partial<_245.ExtendedVoteInfo>): _245.ExtendedVoteInfo;
            fromAmino(object: _245.ExtendedVoteInfoAmino): _245.ExtendedVoteInfo;
            toAmino(message: _245.ExtendedVoteInfo): _245.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _245.ExtendedVoteInfoAminoMsg): _245.ExtendedVoteInfo;
            fromProtoMsg(message: _245.ExtendedVoteInfoProtoMsg): _245.ExtendedVoteInfo;
            toProto(message: _245.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _245.ExtendedVoteInfo): _245.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _245.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Misbehavior;
            fromPartial(object: Partial<_245.Misbehavior>): _245.Misbehavior;
            fromAmino(object: _245.MisbehaviorAmino): _245.Misbehavior;
            toAmino(message: _245.Misbehavior): _245.MisbehaviorAmino;
            fromAminoMsg(object: _245.MisbehaviorAminoMsg): _245.Misbehavior;
            fromProtoMsg(message: _245.MisbehaviorProtoMsg): _245.Misbehavior;
            toProto(message: _245.Misbehavior): Uint8Array;
            toProtoMsg(message: _245.Misbehavior): _245.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _245.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _245.Snapshot;
            fromPartial(object: Partial<_245.Snapshot>): _245.Snapshot;
            fromAmino(object: _245.SnapshotAmino): _245.Snapshot;
            toAmino(message: _245.Snapshot): _245.SnapshotAmino;
            fromAminoMsg(object: _245.SnapshotAminoMsg): _245.Snapshot;
            fromProtoMsg(message: _245.SnapshotProtoMsg): _245.Snapshot;
            toProto(message: _245.Snapshot): Uint8Array;
            toProtoMsg(message: _245.Snapshot): _245.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _247.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _247.Proof;
            fromPartial(object: Partial<_247.Proof>): _247.Proof;
            fromAmino(object: _247.ProofAmino): _247.Proof;
            toAmino(message: _247.Proof): _247.ProofAmino;
            fromAminoMsg(object: _247.ProofAminoMsg): _247.Proof;
            fromProtoMsg(message: _247.ProofProtoMsg): _247.Proof;
            toProto(message: _247.Proof): Uint8Array;
            toProtoMsg(message: _247.Proof): _247.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _247.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _247.ValueOp;
            fromPartial(object: Partial<_247.ValueOp>): _247.ValueOp;
            fromAmino(object: _247.ValueOpAmino): _247.ValueOp;
            toAmino(message: _247.ValueOp): _247.ValueOpAmino;
            fromAminoMsg(object: _247.ValueOpAminoMsg): _247.ValueOp;
            fromProtoMsg(message: _247.ValueOpProtoMsg): _247.ValueOp;
            toProto(message: _247.ValueOp): Uint8Array;
            toProtoMsg(message: _247.ValueOp): _247.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _247.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _247.DominoOp;
            fromPartial(object: Partial<_247.DominoOp>): _247.DominoOp;
            fromAmino(object: _247.DominoOpAmino): _247.DominoOp;
            toAmino(message: _247.DominoOp): _247.DominoOpAmino;
            fromAminoMsg(object: _247.DominoOpAminoMsg): _247.DominoOp;
            fromProtoMsg(message: _247.DominoOpProtoMsg): _247.DominoOp;
            toProto(message: _247.DominoOp): Uint8Array;
            toProtoMsg(message: _247.DominoOp): _247.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _247.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _247.ProofOp;
            fromPartial(object: Partial<_247.ProofOp>): _247.ProofOp;
            fromAmino(object: _247.ProofOpAmino): _247.ProofOp;
            toAmino(message: _247.ProofOp): _247.ProofOpAmino;
            fromAminoMsg(object: _247.ProofOpAminoMsg): _247.ProofOp;
            fromProtoMsg(message: _247.ProofOpProtoMsg): _247.ProofOp;
            toProto(message: _247.ProofOp): Uint8Array;
            toProtoMsg(message: _247.ProofOp): _247.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _247.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _247.ProofOps;
            fromPartial(object: Partial<_247.ProofOps>): _247.ProofOps;
            fromAmino(object: _247.ProofOpsAmino): _247.ProofOps;
            toAmino(message: _247.ProofOps): _247.ProofOpsAmino;
            fromAminoMsg(object: _247.ProofOpsAminoMsg): _247.ProofOps;
            fromProtoMsg(message: _247.ProofOpsProtoMsg): _247.ProofOps;
            toProto(message: _247.ProofOps): Uint8Array;
            toProtoMsg(message: _247.ProofOps): _247.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _246.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _246.PublicKey;
            fromPartial(object: Partial<_246.PublicKey>): _246.PublicKey;
            fromAmino(object: _246.PublicKeyAmino): _246.PublicKey;
            toAmino(message: _246.PublicKey): _246.PublicKeyAmino;
            fromAminoMsg(object: _246.PublicKeyAminoMsg): _246.PublicKey;
            fromProtoMsg(message: _246.PublicKeyProtoMsg): _246.PublicKey;
            toProto(message: _246.PublicKey): Uint8Array;
            toProtoMsg(message: _246.PublicKey): _246.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _248.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: Uint8Array | import("..").BinaryReader, length?: number): _248.BitArray;
                fromPartial(object: Partial<_248.BitArray>): _248.BitArray;
                fromAmino(object: _248.BitArrayAmino): _248.BitArray;
                toAmino(message: _248.BitArray): _248.BitArrayAmino;
                fromAminoMsg(object: _248.BitArrayAminoMsg): _248.BitArray;
                fromProtoMsg(message: _248.BitArrayProtoMsg): _248.BitArray;
                toProto(message: _248.BitArray): Uint8Array;
                toProtoMsg(message: _248.BitArray): _248.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _249.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _249.NetAddress;
            fromPartial(object: Partial<_249.NetAddress>): _249.NetAddress;
            fromAmino(object: _249.NetAddressAmino): _249.NetAddress;
            toAmino(message: _249.NetAddress): _249.NetAddressAmino;
            fromAminoMsg(object: _249.NetAddressAminoMsg): _249.NetAddress;
            fromProtoMsg(message: _249.NetAddressProtoMsg): _249.NetAddress;
            toProto(message: _249.NetAddress): Uint8Array;
            toProtoMsg(message: _249.NetAddress): _249.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _249.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _249.ProtocolVersion;
            fromPartial(object: Partial<_249.ProtocolVersion>): _249.ProtocolVersion;
            fromAmino(object: _249.ProtocolVersionAmino): _249.ProtocolVersion;
            toAmino(message: _249.ProtocolVersion): _249.ProtocolVersionAmino;
            fromAminoMsg(object: _249.ProtocolVersionAminoMsg): _249.ProtocolVersion;
            fromProtoMsg(message: _249.ProtocolVersionProtoMsg): _249.ProtocolVersion;
            toProto(message: _249.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _249.ProtocolVersion): _249.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _249.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _249.DefaultNodeInfo;
            fromPartial(object: Partial<_249.DefaultNodeInfo>): _249.DefaultNodeInfo;
            fromAmino(object: _249.DefaultNodeInfoAmino): _249.DefaultNodeInfo;
            toAmino(message: _249.DefaultNodeInfo): _249.DefaultNodeInfoAmino;
            fromAminoMsg(object: _249.DefaultNodeInfoAminoMsg): _249.DefaultNodeInfo;
            fromProtoMsg(message: _249.DefaultNodeInfoProtoMsg): _249.DefaultNodeInfo;
            toProto(message: _249.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _249.DefaultNodeInfo): _249.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _249.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _249.DefaultNodeInfoOther;
            fromPartial(object: Partial<_249.DefaultNodeInfoOther>): _249.DefaultNodeInfoOther;
            fromAmino(object: _249.DefaultNodeInfoOtherAmino): _249.DefaultNodeInfoOther;
            toAmino(message: _249.DefaultNodeInfoOther): _249.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _249.DefaultNodeInfoOtherAminoMsg): _249.DefaultNodeInfoOther;
            fromProtoMsg(message: _249.DefaultNodeInfoOtherProtoMsg): _249.DefaultNodeInfoOther;
            toProto(message: _249.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _249.DefaultNodeInfoOther): _249.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _254.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _254.ValidatorSet;
            fromPartial(object: Partial<_254.ValidatorSet>): _254.ValidatorSet;
            fromAmino(object: _254.ValidatorSetAmino): _254.ValidatorSet;
            toAmino(message: _254.ValidatorSet): _254.ValidatorSetAmino;
            fromAminoMsg(object: _254.ValidatorSetAminoMsg): _254.ValidatorSet;
            fromProtoMsg(message: _254.ValidatorSetProtoMsg): _254.ValidatorSet;
            toProto(message: _254.ValidatorSet): Uint8Array;
            toProtoMsg(message: _254.ValidatorSet): _254.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _254.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _254.Validator;
            fromPartial(object: Partial<_254.Validator>): _254.Validator;
            fromAmino(object: _254.ValidatorAmino): _254.Validator;
            toAmino(message: _254.Validator): _254.ValidatorAmino;
            fromAminoMsg(object: _254.ValidatorAminoMsg): _254.Validator;
            fromProtoMsg(message: _254.ValidatorProtoMsg): _254.Validator;
            toProto(message: _254.Validator): Uint8Array;
            toProtoMsg(message: _254.Validator): _254.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _254.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _254.SimpleValidator;
            fromPartial(object: Partial<_254.SimpleValidator>): _254.SimpleValidator;
            fromAmino(object: _254.SimpleValidatorAmino): _254.SimpleValidator;
            toAmino(message: _254.SimpleValidator): _254.SimpleValidatorAmino;
            fromAminoMsg(object: _254.SimpleValidatorAminoMsg): _254.SimpleValidator;
            fromProtoMsg(message: _254.SimpleValidatorProtoMsg): _254.SimpleValidator;
            toProto(message: _254.SimpleValidator): Uint8Array;
            toProtoMsg(message: _254.SimpleValidator): _254.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _253.BlockIDFlag;
        blockIDFlagToJSON(object: _253.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _253.SignedMsgType;
        signedMsgTypeToJSON(object: _253.SignedMsgType): string;
        BlockIDFlag: typeof _253.BlockIDFlag;
        BlockIDFlagSDKType: typeof _253.BlockIDFlag;
        BlockIDFlagAmino: typeof _253.BlockIDFlag;
        SignedMsgType: typeof _253.SignedMsgType;
        SignedMsgTypeSDKType: typeof _253.SignedMsgType;
        SignedMsgTypeAmino: typeof _253.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _253.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.PartSetHeader;
            fromPartial(object: Partial<_253.PartSetHeader>): _253.PartSetHeader;
            fromAmino(object: _253.PartSetHeaderAmino): _253.PartSetHeader;
            toAmino(message: _253.PartSetHeader): _253.PartSetHeaderAmino;
            fromAminoMsg(object: _253.PartSetHeaderAminoMsg): _253.PartSetHeader;
            fromProtoMsg(message: _253.PartSetHeaderProtoMsg): _253.PartSetHeader;
            toProto(message: _253.PartSetHeader): Uint8Array;
            toProtoMsg(message: _253.PartSetHeader): _253.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _253.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Part;
            fromPartial(object: Partial<_253.Part>): _253.Part;
            fromAmino(object: _253.PartAmino): _253.Part;
            toAmino(message: _253.Part): _253.PartAmino;
            fromAminoMsg(object: _253.PartAminoMsg): _253.Part;
            fromProtoMsg(message: _253.PartProtoMsg): _253.Part;
            toProto(message: _253.Part): Uint8Array;
            toProtoMsg(message: _253.Part): _253.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _253.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.BlockID;
            fromPartial(object: Partial<_253.BlockID>): _253.BlockID;
            fromAmino(object: _253.BlockIDAmino): _253.BlockID;
            toAmino(message: _253.BlockID): _253.BlockIDAmino;
            fromAminoMsg(object: _253.BlockIDAminoMsg): _253.BlockID;
            fromProtoMsg(message: _253.BlockIDProtoMsg): _253.BlockID;
            toProto(message: _253.BlockID): Uint8Array;
            toProtoMsg(message: _253.BlockID): _253.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _253.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Header;
            fromPartial(object: Partial<_253.Header>): _253.Header;
            fromAmino(object: _253.HeaderAmino): _253.Header;
            toAmino(message: _253.Header): _253.HeaderAmino;
            fromAminoMsg(object: _253.HeaderAminoMsg): _253.Header;
            fromProtoMsg(message: _253.HeaderProtoMsg): _253.Header;
            toProto(message: _253.Header): Uint8Array;
            toProtoMsg(message: _253.Header): _253.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _253.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Data;
            fromPartial(object: Partial<_253.Data>): _253.Data;
            fromAmino(object: _253.DataAmino): _253.Data;
            toAmino(message: _253.Data): _253.DataAmino;
            fromAminoMsg(object: _253.DataAminoMsg): _253.Data;
            fromProtoMsg(message: _253.DataProtoMsg): _253.Data;
            toProto(message: _253.Data): Uint8Array;
            toProtoMsg(message: _253.Data): _253.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _253.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Vote;
            fromPartial(object: Partial<_253.Vote>): _253.Vote;
            fromAmino(object: _253.VoteAmino): _253.Vote;
            toAmino(message: _253.Vote): _253.VoteAmino;
            fromAminoMsg(object: _253.VoteAminoMsg): _253.Vote;
            fromProtoMsg(message: _253.VoteProtoMsg): _253.Vote;
            toProto(message: _253.Vote): Uint8Array;
            toProtoMsg(message: _253.Vote): _253.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _253.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Commit;
            fromPartial(object: Partial<_253.Commit>): _253.Commit;
            fromAmino(object: _253.CommitAmino): _253.Commit;
            toAmino(message: _253.Commit): _253.CommitAmino;
            fromAminoMsg(object: _253.CommitAminoMsg): _253.Commit;
            fromProtoMsg(message: _253.CommitProtoMsg): _253.Commit;
            toProto(message: _253.Commit): Uint8Array;
            toProtoMsg(message: _253.Commit): _253.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _253.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.CommitSig;
            fromPartial(object: Partial<_253.CommitSig>): _253.CommitSig;
            fromAmino(object: _253.CommitSigAmino): _253.CommitSig;
            toAmino(message: _253.CommitSig): _253.CommitSigAmino;
            fromAminoMsg(object: _253.CommitSigAminoMsg): _253.CommitSig;
            fromProtoMsg(message: _253.CommitSigProtoMsg): _253.CommitSig;
            toProto(message: _253.CommitSig): Uint8Array;
            toProtoMsg(message: _253.CommitSig): _253.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _253.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.Proposal;
            fromPartial(object: Partial<_253.Proposal>): _253.Proposal;
            fromAmino(object: _253.ProposalAmino): _253.Proposal;
            toAmino(message: _253.Proposal): _253.ProposalAmino;
            fromAminoMsg(object: _253.ProposalAminoMsg): _253.Proposal;
            fromProtoMsg(message: _253.ProposalProtoMsg): _253.Proposal;
            toProto(message: _253.Proposal): Uint8Array;
            toProtoMsg(message: _253.Proposal): _253.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _253.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.SignedHeader;
            fromPartial(object: Partial<_253.SignedHeader>): _253.SignedHeader;
            fromAmino(object: _253.SignedHeaderAmino): _253.SignedHeader;
            toAmino(message: _253.SignedHeader): _253.SignedHeaderAmino;
            fromAminoMsg(object: _253.SignedHeaderAminoMsg): _253.SignedHeader;
            fromProtoMsg(message: _253.SignedHeaderProtoMsg): _253.SignedHeader;
            toProto(message: _253.SignedHeader): Uint8Array;
            toProtoMsg(message: _253.SignedHeader): _253.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _253.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.LightBlock;
            fromPartial(object: Partial<_253.LightBlock>): _253.LightBlock;
            fromAmino(object: _253.LightBlockAmino): _253.LightBlock;
            toAmino(message: _253.LightBlock): _253.LightBlockAmino;
            fromAminoMsg(object: _253.LightBlockAminoMsg): _253.LightBlock;
            fromProtoMsg(message: _253.LightBlockProtoMsg): _253.LightBlock;
            toProto(message: _253.LightBlock): Uint8Array;
            toProtoMsg(message: _253.LightBlock): _253.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _253.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.BlockMeta;
            fromPartial(object: Partial<_253.BlockMeta>): _253.BlockMeta;
            fromAmino(object: _253.BlockMetaAmino): _253.BlockMeta;
            toAmino(message: _253.BlockMeta): _253.BlockMetaAmino;
            fromAminoMsg(object: _253.BlockMetaAminoMsg): _253.BlockMeta;
            fromProtoMsg(message: _253.BlockMetaProtoMsg): _253.BlockMeta;
            toProto(message: _253.BlockMeta): Uint8Array;
            toProtoMsg(message: _253.BlockMeta): _253.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _253.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _253.TxProof;
            fromPartial(object: Partial<_253.TxProof>): _253.TxProof;
            fromAmino(object: _253.TxProofAmino): _253.TxProof;
            toAmino(message: _253.TxProof): _253.TxProofAmino;
            fromAminoMsg(object: _253.TxProofAminoMsg): _253.TxProof;
            fromProtoMsg(message: _253.TxProofProtoMsg): _253.TxProof;
            toProto(message: _253.TxProof): Uint8Array;
            toProtoMsg(message: _253.TxProof): _253.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _252.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.ConsensusParams;
            fromPartial(object: Partial<_252.ConsensusParams>): _252.ConsensusParams;
            fromAmino(object: _252.ConsensusParamsAmino): _252.ConsensusParams;
            toAmino(message: _252.ConsensusParams): _252.ConsensusParamsAmino;
            fromAminoMsg(object: _252.ConsensusParamsAminoMsg): _252.ConsensusParams;
            fromProtoMsg(message: _252.ConsensusParamsProtoMsg): _252.ConsensusParams;
            toProto(message: _252.ConsensusParams): Uint8Array;
            toProtoMsg(message: _252.ConsensusParams): _252.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _252.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.BlockParams;
            fromPartial(object: Partial<_252.BlockParams>): _252.BlockParams;
            fromAmino(object: _252.BlockParamsAmino): _252.BlockParams;
            toAmino(message: _252.BlockParams): _252.BlockParamsAmino;
            fromAminoMsg(object: _252.BlockParamsAminoMsg): _252.BlockParams;
            fromProtoMsg(message: _252.BlockParamsProtoMsg): _252.BlockParams;
            toProto(message: _252.BlockParams): Uint8Array;
            toProtoMsg(message: _252.BlockParams): _252.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _252.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.EvidenceParams;
            fromPartial(object: Partial<_252.EvidenceParams>): _252.EvidenceParams;
            fromAmino(object: _252.EvidenceParamsAmino): _252.EvidenceParams;
            toAmino(message: _252.EvidenceParams): _252.EvidenceParamsAmino;
            fromAminoMsg(object: _252.EvidenceParamsAminoMsg): _252.EvidenceParams;
            fromProtoMsg(message: _252.EvidenceParamsProtoMsg): _252.EvidenceParams;
            toProto(message: _252.EvidenceParams): Uint8Array;
            toProtoMsg(message: _252.EvidenceParams): _252.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _252.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.ValidatorParams;
            fromPartial(object: Partial<_252.ValidatorParams>): _252.ValidatorParams;
            fromAmino(object: _252.ValidatorParamsAmino): _252.ValidatorParams;
            toAmino(message: _252.ValidatorParams): _252.ValidatorParamsAmino;
            fromAminoMsg(object: _252.ValidatorParamsAminoMsg): _252.ValidatorParams;
            fromProtoMsg(message: _252.ValidatorParamsProtoMsg): _252.ValidatorParams;
            toProto(message: _252.ValidatorParams): Uint8Array;
            toProtoMsg(message: _252.ValidatorParams): _252.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _252.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.VersionParams;
            fromPartial(object: Partial<_252.VersionParams>): _252.VersionParams;
            fromAmino(object: _252.VersionParamsAmino): _252.VersionParams;
            toAmino(message: _252.VersionParams): _252.VersionParamsAmino;
            fromAminoMsg(object: _252.VersionParamsAminoMsg): _252.VersionParams;
            fromProtoMsg(message: _252.VersionParamsProtoMsg): _252.VersionParams;
            toProto(message: _252.VersionParams): Uint8Array;
            toProtoMsg(message: _252.VersionParams): _252.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _252.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _252.HashedParams;
            fromPartial(object: Partial<_252.HashedParams>): _252.HashedParams;
            fromAmino(object: _252.HashedParamsAmino): _252.HashedParams;
            toAmino(message: _252.HashedParams): _252.HashedParamsAmino;
            fromAminoMsg(object: _252.HashedParamsAminoMsg): _252.HashedParams;
            fromProtoMsg(message: _252.HashedParamsProtoMsg): _252.HashedParams;
            toProto(message: _252.HashedParams): Uint8Array;
            toProtoMsg(message: _252.HashedParams): _252.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _251.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _251.Evidence;
            fromPartial(object: Partial<_251.Evidence>): _251.Evidence;
            fromAmino(object: _251.EvidenceAmino): _251.Evidence;
            toAmino(message: _251.Evidence): _251.EvidenceAmino;
            fromAminoMsg(object: _251.EvidenceAminoMsg): _251.Evidence;
            fromProtoMsg(message: _251.EvidenceProtoMsg): _251.Evidence;
            toProto(message: _251.Evidence): Uint8Array;
            toProtoMsg(message: _251.Evidence): _251.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _251.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _251.DuplicateVoteEvidence;
            fromPartial(object: Partial<_251.DuplicateVoteEvidence>): _251.DuplicateVoteEvidence;
            fromAmino(object: _251.DuplicateVoteEvidenceAmino): _251.DuplicateVoteEvidence;
            toAmino(message: _251.DuplicateVoteEvidence): _251.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _251.DuplicateVoteEvidenceAminoMsg): _251.DuplicateVoteEvidence;
            fromProtoMsg(message: _251.DuplicateVoteEvidenceProtoMsg): _251.DuplicateVoteEvidence;
            toProto(message: _251.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _251.DuplicateVoteEvidence): _251.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _251.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _251.LightClientAttackEvidence;
            fromPartial(object: Partial<_251.LightClientAttackEvidence>): _251.LightClientAttackEvidence;
            fromAmino(object: _251.LightClientAttackEvidenceAmino): _251.LightClientAttackEvidence;
            toAmino(message: _251.LightClientAttackEvidence): _251.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _251.LightClientAttackEvidenceAminoMsg): _251.LightClientAttackEvidence;
            fromProtoMsg(message: _251.LightClientAttackEvidenceProtoMsg): _251.LightClientAttackEvidence;
            toProto(message: _251.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _251.LightClientAttackEvidence): _251.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _251.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _251.EvidenceList;
            fromPartial(object: Partial<_251.EvidenceList>): _251.EvidenceList;
            fromAmino(object: _251.EvidenceListAmino): _251.EvidenceList;
            toAmino(message: _251.EvidenceList): _251.EvidenceListAmino;
            fromAminoMsg(object: _251.EvidenceListAminoMsg): _251.EvidenceList;
            fromProtoMsg(message: _251.EvidenceListProtoMsg): _251.EvidenceList;
            toProto(message: _251.EvidenceList): Uint8Array;
            toProtoMsg(message: _251.EvidenceList): _251.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _250.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _250.Block;
            fromPartial(object: Partial<_250.Block>): _250.Block;
            fromAmino(object: _250.BlockAmino): _250.Block;
            toAmino(message: _250.Block): _250.BlockAmino;
            fromAminoMsg(object: _250.BlockAminoMsg): _250.Block;
            fromProtoMsg(message: _250.BlockProtoMsg): _250.Block;
            toProto(message: _250.Block): Uint8Array;
            toProtoMsg(message: _250.Block): _250.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _255.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _255.App;
            fromPartial(object: Partial<_255.App>): _255.App;
            fromAmino(object: _255.AppAmino): _255.App;
            toAmino(message: _255.App): _255.AppAmino;
            fromAminoMsg(object: _255.AppAminoMsg): _255.App;
            fromProtoMsg(message: _255.AppProtoMsg): _255.App;
            toProto(message: _255.App): Uint8Array;
            toProtoMsg(message: _255.App): _255.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _255.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _255.Consensus;
            fromPartial(object: Partial<_255.Consensus>): _255.Consensus;
            fromAmino(object: _255.ConsensusAmino): _255.Consensus;
            toAmino(message: _255.Consensus): _255.ConsensusAmino;
            fromAminoMsg(object: _255.ConsensusAminoMsg): _255.Consensus;
            fromProtoMsg(message: _255.ConsensusProtoMsg): _255.Consensus;
            toProto(message: _255.Consensus): Uint8Array;
            toProtoMsg(message: _255.Consensus): _255.ConsensusProtoMsg;
        };
    };
}
