import * as _183 from "./abci/types";
import * as _184 from "./crypto/keys";
import * as _185 from "./crypto/proof";
import * as _186 from "./libs/bits/types";
import * as _187 from "./p2p/types";
import * as _188 from "./types/block";
import * as _189 from "./types/evidence";
import * as _190 from "./types/params";
import * as _191 from "./types/types";
import * as _192 from "./types/validator";
import * as _193 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _183.CheckTxType;
        checkTxTypeToJSON(object: _183.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _183.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _183.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _183.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _183.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _183.EvidenceType;
        evidenceTypeToJSON(object: _183.EvidenceType): string;
        CheckTxType: typeof _183.CheckTxType;
        CheckTxTypeSDKType: typeof _183.CheckTxType;
        CheckTxTypeAmino: typeof _183.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _183.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _183.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _183.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _183.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _183.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _183.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _183.EvidenceType;
        EvidenceTypeSDKType: typeof _183.EvidenceType;
        EvidenceTypeAmino: typeof _183.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _183.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Request;
            fromPartial(object: Partial<_183.Request>): _183.Request;
            fromAmino(object: _183.RequestAmino): _183.Request;
            toAmino(message: _183.Request): _183.RequestAmino;
            fromAminoMsg(object: _183.RequestAminoMsg): _183.Request;
            fromProtoMsg(message: _183.RequestProtoMsg): _183.Request;
            toProto(message: _183.Request): Uint8Array;
            toProtoMsg(message: _183.Request): _183.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _183.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestEcho;
            fromPartial(object: Partial<_183.RequestEcho>): _183.RequestEcho;
            fromAmino(object: _183.RequestEchoAmino): _183.RequestEcho;
            toAmino(message: _183.RequestEcho): _183.RequestEchoAmino;
            fromAminoMsg(object: _183.RequestEchoAminoMsg): _183.RequestEcho;
            fromProtoMsg(message: _183.RequestEchoProtoMsg): _183.RequestEcho;
            toProto(message: _183.RequestEcho): Uint8Array;
            toProtoMsg(message: _183.RequestEcho): _183.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _183.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestFlush;
            fromPartial(_: Partial<_183.RequestFlush>): _183.RequestFlush;
            fromAmino(_: _183.RequestFlushAmino): _183.RequestFlush;
            toAmino(_: _183.RequestFlush): _183.RequestFlushAmino;
            fromAminoMsg(object: _183.RequestFlushAminoMsg): _183.RequestFlush;
            fromProtoMsg(message: _183.RequestFlushProtoMsg): _183.RequestFlush;
            toProto(message: _183.RequestFlush): Uint8Array;
            toProtoMsg(message: _183.RequestFlush): _183.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _183.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestInfo;
            fromPartial(object: Partial<_183.RequestInfo>): _183.RequestInfo;
            fromAmino(object: _183.RequestInfoAmino): _183.RequestInfo;
            toAmino(message: _183.RequestInfo): _183.RequestInfoAmino;
            fromAminoMsg(object: _183.RequestInfoAminoMsg): _183.RequestInfo;
            fromProtoMsg(message: _183.RequestInfoProtoMsg): _183.RequestInfo;
            toProto(message: _183.RequestInfo): Uint8Array;
            toProtoMsg(message: _183.RequestInfo): _183.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _183.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestSetOption;
            fromPartial(object: Partial<_183.RequestSetOption>): _183.RequestSetOption;
            fromAmino(object: _183.RequestSetOptionAmino): _183.RequestSetOption;
            toAmino(message: _183.RequestSetOption): _183.RequestSetOptionAmino;
            fromAminoMsg(object: _183.RequestSetOptionAminoMsg): _183.RequestSetOption;
            fromProtoMsg(message: _183.RequestSetOptionProtoMsg): _183.RequestSetOption;
            toProto(message: _183.RequestSetOption): Uint8Array;
            toProtoMsg(message: _183.RequestSetOption): _183.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _183.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestInitChain;
            fromPartial(object: Partial<_183.RequestInitChain>): _183.RequestInitChain;
            fromAmino(object: _183.RequestInitChainAmino): _183.RequestInitChain;
            toAmino(message: _183.RequestInitChain): _183.RequestInitChainAmino;
            fromAminoMsg(object: _183.RequestInitChainAminoMsg): _183.RequestInitChain;
            fromProtoMsg(message: _183.RequestInitChainProtoMsg): _183.RequestInitChain;
            toProto(message: _183.RequestInitChain): Uint8Array;
            toProtoMsg(message: _183.RequestInitChain): _183.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _183.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestQuery;
            fromPartial(object: Partial<_183.RequestQuery>): _183.RequestQuery;
            fromAmino(object: _183.RequestQueryAmino): _183.RequestQuery;
            toAmino(message: _183.RequestQuery): _183.RequestQueryAmino;
            fromAminoMsg(object: _183.RequestQueryAminoMsg): _183.RequestQuery;
            fromProtoMsg(message: _183.RequestQueryProtoMsg): _183.RequestQuery;
            toProto(message: _183.RequestQuery): Uint8Array;
            toProtoMsg(message: _183.RequestQuery): _183.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _183.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestBeginBlock;
            fromPartial(object: Partial<_183.RequestBeginBlock>): _183.RequestBeginBlock;
            fromAmino(object: _183.RequestBeginBlockAmino): _183.RequestBeginBlock;
            toAmino(message: _183.RequestBeginBlock): _183.RequestBeginBlockAmino;
            fromAminoMsg(object: _183.RequestBeginBlockAminoMsg): _183.RequestBeginBlock;
            fromProtoMsg(message: _183.RequestBeginBlockProtoMsg): _183.RequestBeginBlock;
            toProto(message: _183.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _183.RequestBeginBlock): _183.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _183.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestCheckTx;
            fromPartial(object: Partial<_183.RequestCheckTx>): _183.RequestCheckTx;
            fromAmino(object: _183.RequestCheckTxAmino): _183.RequestCheckTx;
            toAmino(message: _183.RequestCheckTx): _183.RequestCheckTxAmino;
            fromAminoMsg(object: _183.RequestCheckTxAminoMsg): _183.RequestCheckTx;
            fromProtoMsg(message: _183.RequestCheckTxProtoMsg): _183.RequestCheckTx;
            toProto(message: _183.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _183.RequestCheckTx): _183.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _183.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestDeliverTx;
            fromPartial(object: Partial<_183.RequestDeliverTx>): _183.RequestDeliverTx;
            fromAmino(object: _183.RequestDeliverTxAmino): _183.RequestDeliverTx;
            toAmino(message: _183.RequestDeliverTx): _183.RequestDeliverTxAmino;
            fromAminoMsg(object: _183.RequestDeliverTxAminoMsg): _183.RequestDeliverTx;
            fromProtoMsg(message: _183.RequestDeliverTxProtoMsg): _183.RequestDeliverTx;
            toProto(message: _183.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _183.RequestDeliverTx): _183.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _183.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestEndBlock;
            fromPartial(object: Partial<_183.RequestEndBlock>): _183.RequestEndBlock;
            fromAmino(object: _183.RequestEndBlockAmino): _183.RequestEndBlock;
            toAmino(message: _183.RequestEndBlock): _183.RequestEndBlockAmino;
            fromAminoMsg(object: _183.RequestEndBlockAminoMsg): _183.RequestEndBlock;
            fromProtoMsg(message: _183.RequestEndBlockProtoMsg): _183.RequestEndBlock;
            toProto(message: _183.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _183.RequestEndBlock): _183.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _183.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestCommit;
            fromPartial(_: Partial<_183.RequestCommit>): _183.RequestCommit;
            fromAmino(_: _183.RequestCommitAmino): _183.RequestCommit;
            toAmino(_: _183.RequestCommit): _183.RequestCommitAmino;
            fromAminoMsg(object: _183.RequestCommitAminoMsg): _183.RequestCommit;
            fromProtoMsg(message: _183.RequestCommitProtoMsg): _183.RequestCommit;
            toProto(message: _183.RequestCommit): Uint8Array;
            toProtoMsg(message: _183.RequestCommit): _183.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _183.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestListSnapshots;
            fromPartial(_: Partial<_183.RequestListSnapshots>): _183.RequestListSnapshots;
            fromAmino(_: _183.RequestListSnapshotsAmino): _183.RequestListSnapshots;
            toAmino(_: _183.RequestListSnapshots): _183.RequestListSnapshotsAmino;
            fromAminoMsg(object: _183.RequestListSnapshotsAminoMsg): _183.RequestListSnapshots;
            fromProtoMsg(message: _183.RequestListSnapshotsProtoMsg): _183.RequestListSnapshots;
            toProto(message: _183.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _183.RequestListSnapshots): _183.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _183.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestOfferSnapshot;
            fromPartial(object: Partial<_183.RequestOfferSnapshot>): _183.RequestOfferSnapshot;
            fromAmino(object: _183.RequestOfferSnapshotAmino): _183.RequestOfferSnapshot;
            toAmino(message: _183.RequestOfferSnapshot): _183.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _183.RequestOfferSnapshotAminoMsg): _183.RequestOfferSnapshot;
            fromProtoMsg(message: _183.RequestOfferSnapshotProtoMsg): _183.RequestOfferSnapshot;
            toProto(message: _183.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _183.RequestOfferSnapshot): _183.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _183.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_183.RequestLoadSnapshotChunk>): _183.RequestLoadSnapshotChunk;
            fromAmino(object: _183.RequestLoadSnapshotChunkAmino): _183.RequestLoadSnapshotChunk;
            toAmino(message: _183.RequestLoadSnapshotChunk): _183.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _183.RequestLoadSnapshotChunkAminoMsg): _183.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _183.RequestLoadSnapshotChunkProtoMsg): _183.RequestLoadSnapshotChunk;
            toProto(message: _183.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _183.RequestLoadSnapshotChunk): _183.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _183.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_183.RequestApplySnapshotChunk>): _183.RequestApplySnapshotChunk;
            fromAmino(object: _183.RequestApplySnapshotChunkAmino): _183.RequestApplySnapshotChunk;
            toAmino(message: _183.RequestApplySnapshotChunk): _183.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _183.RequestApplySnapshotChunkAminoMsg): _183.RequestApplySnapshotChunk;
            fromProtoMsg(message: _183.RequestApplySnapshotChunkProtoMsg): _183.RequestApplySnapshotChunk;
            toProto(message: _183.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _183.RequestApplySnapshotChunk): _183.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _183.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Response;
            fromPartial(object: Partial<_183.Response>): _183.Response;
            fromAmino(object: _183.ResponseAmino): _183.Response;
            toAmino(message: _183.Response): _183.ResponseAmino;
            fromAminoMsg(object: _183.ResponseAminoMsg): _183.Response;
            fromProtoMsg(message: _183.ResponseProtoMsg): _183.Response;
            toProto(message: _183.Response): Uint8Array;
            toProtoMsg(message: _183.Response): _183.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _183.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseException;
            fromPartial(object: Partial<_183.ResponseException>): _183.ResponseException;
            fromAmino(object: _183.ResponseExceptionAmino): _183.ResponseException;
            toAmino(message: _183.ResponseException): _183.ResponseExceptionAmino;
            fromAminoMsg(object: _183.ResponseExceptionAminoMsg): _183.ResponseException;
            fromProtoMsg(message: _183.ResponseExceptionProtoMsg): _183.ResponseException;
            toProto(message: _183.ResponseException): Uint8Array;
            toProtoMsg(message: _183.ResponseException): _183.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _183.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseEcho;
            fromPartial(object: Partial<_183.ResponseEcho>): _183.ResponseEcho;
            fromAmino(object: _183.ResponseEchoAmino): _183.ResponseEcho;
            toAmino(message: _183.ResponseEcho): _183.ResponseEchoAmino;
            fromAminoMsg(object: _183.ResponseEchoAminoMsg): _183.ResponseEcho;
            fromProtoMsg(message: _183.ResponseEchoProtoMsg): _183.ResponseEcho;
            toProto(message: _183.ResponseEcho): Uint8Array;
            toProtoMsg(message: _183.ResponseEcho): _183.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _183.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseFlush;
            fromPartial(_: Partial<_183.ResponseFlush>): _183.ResponseFlush;
            fromAmino(_: _183.ResponseFlushAmino): _183.ResponseFlush;
            toAmino(_: _183.ResponseFlush): _183.ResponseFlushAmino;
            fromAminoMsg(object: _183.ResponseFlushAminoMsg): _183.ResponseFlush;
            fromProtoMsg(message: _183.ResponseFlushProtoMsg): _183.ResponseFlush;
            toProto(message: _183.ResponseFlush): Uint8Array;
            toProtoMsg(message: _183.ResponseFlush): _183.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _183.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseInfo;
            fromPartial(object: Partial<_183.ResponseInfo>): _183.ResponseInfo;
            fromAmino(object: _183.ResponseInfoAmino): _183.ResponseInfo;
            toAmino(message: _183.ResponseInfo): _183.ResponseInfoAmino;
            fromAminoMsg(object: _183.ResponseInfoAminoMsg): _183.ResponseInfo;
            fromProtoMsg(message: _183.ResponseInfoProtoMsg): _183.ResponseInfo;
            toProto(message: _183.ResponseInfo): Uint8Array;
            toProtoMsg(message: _183.ResponseInfo): _183.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _183.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseSetOption;
            fromPartial(object: Partial<_183.ResponseSetOption>): _183.ResponseSetOption;
            fromAmino(object: _183.ResponseSetOptionAmino): _183.ResponseSetOption;
            toAmino(message: _183.ResponseSetOption): _183.ResponseSetOptionAmino;
            fromAminoMsg(object: _183.ResponseSetOptionAminoMsg): _183.ResponseSetOption;
            fromProtoMsg(message: _183.ResponseSetOptionProtoMsg): _183.ResponseSetOption;
            toProto(message: _183.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _183.ResponseSetOption): _183.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _183.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseInitChain;
            fromPartial(object: Partial<_183.ResponseInitChain>): _183.ResponseInitChain;
            fromAmino(object: _183.ResponseInitChainAmino): _183.ResponseInitChain;
            toAmino(message: _183.ResponseInitChain): _183.ResponseInitChainAmino;
            fromAminoMsg(object: _183.ResponseInitChainAminoMsg): _183.ResponseInitChain;
            fromProtoMsg(message: _183.ResponseInitChainProtoMsg): _183.ResponseInitChain;
            toProto(message: _183.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _183.ResponseInitChain): _183.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _183.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseQuery;
            fromPartial(object: Partial<_183.ResponseQuery>): _183.ResponseQuery;
            fromAmino(object: _183.ResponseQueryAmino): _183.ResponseQuery;
            toAmino(message: _183.ResponseQuery): _183.ResponseQueryAmino;
            fromAminoMsg(object: _183.ResponseQueryAminoMsg): _183.ResponseQuery;
            fromProtoMsg(message: _183.ResponseQueryProtoMsg): _183.ResponseQuery;
            toProto(message: _183.ResponseQuery): Uint8Array;
            toProtoMsg(message: _183.ResponseQuery): _183.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _183.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseBeginBlock;
            fromPartial(object: Partial<_183.ResponseBeginBlock>): _183.ResponseBeginBlock;
            fromAmino(object: _183.ResponseBeginBlockAmino): _183.ResponseBeginBlock;
            toAmino(message: _183.ResponseBeginBlock): _183.ResponseBeginBlockAmino;
            fromAminoMsg(object: _183.ResponseBeginBlockAminoMsg): _183.ResponseBeginBlock;
            fromProtoMsg(message: _183.ResponseBeginBlockProtoMsg): _183.ResponseBeginBlock;
            toProto(message: _183.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _183.ResponseBeginBlock): _183.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _183.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseCheckTx;
            fromPartial(object: Partial<_183.ResponseCheckTx>): _183.ResponseCheckTx;
            fromAmino(object: _183.ResponseCheckTxAmino): _183.ResponseCheckTx;
            toAmino(message: _183.ResponseCheckTx): _183.ResponseCheckTxAmino;
            fromAminoMsg(object: _183.ResponseCheckTxAminoMsg): _183.ResponseCheckTx;
            fromProtoMsg(message: _183.ResponseCheckTxProtoMsg): _183.ResponseCheckTx;
            toProto(message: _183.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _183.ResponseCheckTx): _183.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _183.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseDeliverTx;
            fromPartial(object: Partial<_183.ResponseDeliverTx>): _183.ResponseDeliverTx;
            fromAmino(object: _183.ResponseDeliverTxAmino): _183.ResponseDeliverTx;
            toAmino(message: _183.ResponseDeliverTx): _183.ResponseDeliverTxAmino;
            fromAminoMsg(object: _183.ResponseDeliverTxAminoMsg): _183.ResponseDeliverTx;
            fromProtoMsg(message: _183.ResponseDeliverTxProtoMsg): _183.ResponseDeliverTx;
            toProto(message: _183.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _183.ResponseDeliverTx): _183.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _183.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseEndBlock;
            fromPartial(object: Partial<_183.ResponseEndBlock>): _183.ResponseEndBlock;
            fromAmino(object: _183.ResponseEndBlockAmino): _183.ResponseEndBlock;
            toAmino(message: _183.ResponseEndBlock): _183.ResponseEndBlockAmino;
            fromAminoMsg(object: _183.ResponseEndBlockAminoMsg): _183.ResponseEndBlock;
            fromProtoMsg(message: _183.ResponseEndBlockProtoMsg): _183.ResponseEndBlock;
            toProto(message: _183.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _183.ResponseEndBlock): _183.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _183.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseCommit;
            fromPartial(object: Partial<_183.ResponseCommit>): _183.ResponseCommit;
            fromAmino(object: _183.ResponseCommitAmino): _183.ResponseCommit;
            toAmino(message: _183.ResponseCommit): _183.ResponseCommitAmino;
            fromAminoMsg(object: _183.ResponseCommitAminoMsg): _183.ResponseCommit;
            fromProtoMsg(message: _183.ResponseCommitProtoMsg): _183.ResponseCommit;
            toProto(message: _183.ResponseCommit): Uint8Array;
            toProtoMsg(message: _183.ResponseCommit): _183.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _183.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseListSnapshots;
            fromPartial(object: Partial<_183.ResponseListSnapshots>): _183.ResponseListSnapshots;
            fromAmino(object: _183.ResponseListSnapshotsAmino): _183.ResponseListSnapshots;
            toAmino(message: _183.ResponseListSnapshots): _183.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _183.ResponseListSnapshotsAminoMsg): _183.ResponseListSnapshots;
            fromProtoMsg(message: _183.ResponseListSnapshotsProtoMsg): _183.ResponseListSnapshots;
            toProto(message: _183.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _183.ResponseListSnapshots): _183.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _183.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseOfferSnapshot;
            fromPartial(object: Partial<_183.ResponseOfferSnapshot>): _183.ResponseOfferSnapshot;
            fromAmino(object: _183.ResponseOfferSnapshotAmino): _183.ResponseOfferSnapshot;
            toAmino(message: _183.ResponseOfferSnapshot): _183.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _183.ResponseOfferSnapshotAminoMsg): _183.ResponseOfferSnapshot;
            fromProtoMsg(message: _183.ResponseOfferSnapshotProtoMsg): _183.ResponseOfferSnapshot;
            toProto(message: _183.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _183.ResponseOfferSnapshot): _183.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _183.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_183.ResponseLoadSnapshotChunk>): _183.ResponseLoadSnapshotChunk;
            fromAmino(object: _183.ResponseLoadSnapshotChunkAmino): _183.ResponseLoadSnapshotChunk;
            toAmino(message: _183.ResponseLoadSnapshotChunk): _183.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _183.ResponseLoadSnapshotChunkAminoMsg): _183.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _183.ResponseLoadSnapshotChunkProtoMsg): _183.ResponseLoadSnapshotChunk;
            toProto(message: _183.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _183.ResponseLoadSnapshotChunk): _183.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _183.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_183.ResponseApplySnapshotChunk>): _183.ResponseApplySnapshotChunk;
            fromAmino(object: _183.ResponseApplySnapshotChunkAmino): _183.ResponseApplySnapshotChunk;
            toAmino(message: _183.ResponseApplySnapshotChunk): _183.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _183.ResponseApplySnapshotChunkAminoMsg): _183.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _183.ResponseApplySnapshotChunkProtoMsg): _183.ResponseApplySnapshotChunk;
            toProto(message: _183.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _183.ResponseApplySnapshotChunk): _183.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _183.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ConsensusParams;
            fromPartial(object: Partial<_183.ConsensusParams>): _183.ConsensusParams;
            fromAmino(object: _183.ConsensusParamsAmino): _183.ConsensusParams;
            toAmino(message: _183.ConsensusParams): _183.ConsensusParamsAmino;
            fromAminoMsg(object: _183.ConsensusParamsAminoMsg): _183.ConsensusParams;
            fromProtoMsg(message: _183.ConsensusParamsProtoMsg): _183.ConsensusParams;
            toProto(message: _183.ConsensusParams): Uint8Array;
            toProtoMsg(message: _183.ConsensusParams): _183.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _183.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.BlockParams;
            fromPartial(object: Partial<_183.BlockParams>): _183.BlockParams;
            fromAmino(object: _183.BlockParamsAmino): _183.BlockParams;
            toAmino(message: _183.BlockParams): _183.BlockParamsAmino;
            fromAminoMsg(object: _183.BlockParamsAminoMsg): _183.BlockParams;
            fromProtoMsg(message: _183.BlockParamsProtoMsg): _183.BlockParams;
            toProto(message: _183.BlockParams): Uint8Array;
            toProtoMsg(message: _183.BlockParams): _183.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _183.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.LastCommitInfo;
            fromPartial(object: Partial<_183.LastCommitInfo>): _183.LastCommitInfo;
            fromAmino(object: _183.LastCommitInfoAmino): _183.LastCommitInfo;
            toAmino(message: _183.LastCommitInfo): _183.LastCommitInfoAmino;
            fromAminoMsg(object: _183.LastCommitInfoAminoMsg): _183.LastCommitInfo;
            fromProtoMsg(message: _183.LastCommitInfoProtoMsg): _183.LastCommitInfo;
            toProto(message: _183.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _183.LastCommitInfo): _183.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _183.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Event;
            fromPartial(object: Partial<_183.Event>): _183.Event;
            fromAmino(object: _183.EventAmino): _183.Event;
            toAmino(message: _183.Event): _183.EventAmino;
            fromAminoMsg(object: _183.EventAminoMsg): _183.Event;
            fromProtoMsg(message: _183.EventProtoMsg): _183.Event;
            toProto(message: _183.Event): Uint8Array;
            toProtoMsg(message: _183.Event): _183.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _183.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.EventAttribute;
            fromPartial(object: Partial<_183.EventAttribute>): _183.EventAttribute;
            fromAmino(object: _183.EventAttributeAmino): _183.EventAttribute;
            toAmino(message: _183.EventAttribute): _183.EventAttributeAmino;
            fromAminoMsg(object: _183.EventAttributeAminoMsg): _183.EventAttribute;
            fromProtoMsg(message: _183.EventAttributeProtoMsg): _183.EventAttribute;
            toProto(message: _183.EventAttribute): Uint8Array;
            toProtoMsg(message: _183.EventAttribute): _183.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _183.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.TxResult;
            fromPartial(object: Partial<_183.TxResult>): _183.TxResult;
            fromAmino(object: _183.TxResultAmino): _183.TxResult;
            toAmino(message: _183.TxResult): _183.TxResultAmino;
            fromAminoMsg(object: _183.TxResultAminoMsg): _183.TxResult;
            fromProtoMsg(message: _183.TxResultProtoMsg): _183.TxResult;
            toProto(message: _183.TxResult): Uint8Array;
            toProtoMsg(message: _183.TxResult): _183.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _183.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Validator;
            fromPartial(object: Partial<_183.Validator>): _183.Validator;
            fromAmino(object: _183.ValidatorAmino): _183.Validator;
            toAmino(message: _183.Validator): _183.ValidatorAmino;
            fromAminoMsg(object: _183.ValidatorAminoMsg): _183.Validator;
            fromProtoMsg(message: _183.ValidatorProtoMsg): _183.Validator;
            toProto(message: _183.Validator): Uint8Array;
            toProtoMsg(message: _183.Validator): _183.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _183.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.ValidatorUpdate;
            fromPartial(object: Partial<_183.ValidatorUpdate>): _183.ValidatorUpdate;
            fromAmino(object: _183.ValidatorUpdateAmino): _183.ValidatorUpdate;
            toAmino(message: _183.ValidatorUpdate): _183.ValidatorUpdateAmino;
            fromAminoMsg(object: _183.ValidatorUpdateAminoMsg): _183.ValidatorUpdate;
            fromProtoMsg(message: _183.ValidatorUpdateProtoMsg): _183.ValidatorUpdate;
            toProto(message: _183.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _183.ValidatorUpdate): _183.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _183.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.VoteInfo;
            fromPartial(object: Partial<_183.VoteInfo>): _183.VoteInfo;
            fromAmino(object: _183.VoteInfoAmino): _183.VoteInfo;
            toAmino(message: _183.VoteInfo): _183.VoteInfoAmino;
            fromAminoMsg(object: _183.VoteInfoAminoMsg): _183.VoteInfo;
            fromProtoMsg(message: _183.VoteInfoProtoMsg): _183.VoteInfo;
            toProto(message: _183.VoteInfo): Uint8Array;
            toProtoMsg(message: _183.VoteInfo): _183.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _183.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Evidence;
            fromPartial(object: Partial<_183.Evidence>): _183.Evidence;
            fromAmino(object: _183.EvidenceAmino): _183.Evidence;
            toAmino(message: _183.Evidence): _183.EvidenceAmino;
            fromAminoMsg(object: _183.EvidenceAminoMsg): _183.Evidence;
            fromProtoMsg(message: _183.EvidenceProtoMsg): _183.Evidence;
            toProto(message: _183.Evidence): Uint8Array;
            toProtoMsg(message: _183.Evidence): _183.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _183.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _183.Snapshot;
            fromPartial(object: Partial<_183.Snapshot>): _183.Snapshot;
            fromAmino(object: _183.SnapshotAmino): _183.Snapshot;
            toAmino(message: _183.Snapshot): _183.SnapshotAmino;
            fromAminoMsg(object: _183.SnapshotAminoMsg): _183.Snapshot;
            fromProtoMsg(message: _183.SnapshotProtoMsg): _183.Snapshot;
            toProto(message: _183.Snapshot): Uint8Array;
            toProtoMsg(message: _183.Snapshot): _183.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _185.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _185.Proof;
            fromPartial(object: Partial<_185.Proof>): _185.Proof;
            fromAmino(object: _185.ProofAmino): _185.Proof;
            toAmino(message: _185.Proof): _185.ProofAmino;
            fromAminoMsg(object: _185.ProofAminoMsg): _185.Proof;
            fromProtoMsg(message: _185.ProofProtoMsg): _185.Proof;
            toProto(message: _185.Proof): Uint8Array;
            toProtoMsg(message: _185.Proof): _185.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _185.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _185.ValueOp;
            fromPartial(object: Partial<_185.ValueOp>): _185.ValueOp;
            fromAmino(object: _185.ValueOpAmino): _185.ValueOp;
            toAmino(message: _185.ValueOp): _185.ValueOpAmino;
            fromAminoMsg(object: _185.ValueOpAminoMsg): _185.ValueOp;
            fromProtoMsg(message: _185.ValueOpProtoMsg): _185.ValueOp;
            toProto(message: _185.ValueOp): Uint8Array;
            toProtoMsg(message: _185.ValueOp): _185.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _185.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _185.DominoOp;
            fromPartial(object: Partial<_185.DominoOp>): _185.DominoOp;
            fromAmino(object: _185.DominoOpAmino): _185.DominoOp;
            toAmino(message: _185.DominoOp): _185.DominoOpAmino;
            fromAminoMsg(object: _185.DominoOpAminoMsg): _185.DominoOp;
            fromProtoMsg(message: _185.DominoOpProtoMsg): _185.DominoOp;
            toProto(message: _185.DominoOp): Uint8Array;
            toProtoMsg(message: _185.DominoOp): _185.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _185.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _185.ProofOp;
            fromPartial(object: Partial<_185.ProofOp>): _185.ProofOp;
            fromAmino(object: _185.ProofOpAmino): _185.ProofOp;
            toAmino(message: _185.ProofOp): _185.ProofOpAmino;
            fromAminoMsg(object: _185.ProofOpAminoMsg): _185.ProofOp;
            fromProtoMsg(message: _185.ProofOpProtoMsg): _185.ProofOp;
            toProto(message: _185.ProofOp): Uint8Array;
            toProtoMsg(message: _185.ProofOp): _185.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _185.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _185.ProofOps;
            fromPartial(object: Partial<_185.ProofOps>): _185.ProofOps;
            fromAmino(object: _185.ProofOpsAmino): _185.ProofOps;
            toAmino(message: _185.ProofOps): _185.ProofOpsAmino;
            fromAminoMsg(object: _185.ProofOpsAminoMsg): _185.ProofOps;
            fromProtoMsg(message: _185.ProofOpsProtoMsg): _185.ProofOps;
            toProto(message: _185.ProofOps): Uint8Array;
            toProtoMsg(message: _185.ProofOps): _185.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _184.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _184.PublicKey;
            fromPartial(object: Partial<_184.PublicKey>): _184.PublicKey;
            fromAmino(object: _184.PublicKeyAmino): _184.PublicKey;
            toAmino(message: _184.PublicKey): _184.PublicKeyAmino;
            fromAminoMsg(object: _184.PublicKeyAminoMsg): _184.PublicKey;
            fromProtoMsg(message: _184.PublicKeyProtoMsg): _184.PublicKey;
            toProto(message: _184.PublicKey): Uint8Array;
            toProtoMsg(message: _184.PublicKey): _184.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _186.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: Uint8Array | import("..").BinaryReader, length?: number): _186.BitArray;
                fromPartial(object: Partial<_186.BitArray>): _186.BitArray;
                fromAmino(object: _186.BitArrayAmino): _186.BitArray;
                toAmino(message: _186.BitArray): _186.BitArrayAmino;
                fromAminoMsg(object: _186.BitArrayAminoMsg): _186.BitArray;
                fromProtoMsg(message: _186.BitArrayProtoMsg): _186.BitArray;
                toProto(message: _186.BitArray): Uint8Array;
                toProtoMsg(message: _186.BitArray): _186.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _187.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _187.NetAddress;
            fromPartial(object: Partial<_187.NetAddress>): _187.NetAddress;
            fromAmino(object: _187.NetAddressAmino): _187.NetAddress;
            toAmino(message: _187.NetAddress): _187.NetAddressAmino;
            fromAminoMsg(object: _187.NetAddressAminoMsg): _187.NetAddress;
            fromProtoMsg(message: _187.NetAddressProtoMsg): _187.NetAddress;
            toProto(message: _187.NetAddress): Uint8Array;
            toProtoMsg(message: _187.NetAddress): _187.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _187.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _187.ProtocolVersion;
            fromPartial(object: Partial<_187.ProtocolVersion>): _187.ProtocolVersion;
            fromAmino(object: _187.ProtocolVersionAmino): _187.ProtocolVersion;
            toAmino(message: _187.ProtocolVersion): _187.ProtocolVersionAmino;
            fromAminoMsg(object: _187.ProtocolVersionAminoMsg): _187.ProtocolVersion;
            fromProtoMsg(message: _187.ProtocolVersionProtoMsg): _187.ProtocolVersion;
            toProto(message: _187.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _187.ProtocolVersion): _187.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _187.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _187.DefaultNodeInfo;
            fromPartial(object: Partial<_187.DefaultNodeInfo>): _187.DefaultNodeInfo;
            fromAmino(object: _187.DefaultNodeInfoAmino): _187.DefaultNodeInfo;
            toAmino(message: _187.DefaultNodeInfo): _187.DefaultNodeInfoAmino;
            fromAminoMsg(object: _187.DefaultNodeInfoAminoMsg): _187.DefaultNodeInfo;
            fromProtoMsg(message: _187.DefaultNodeInfoProtoMsg): _187.DefaultNodeInfo;
            toProto(message: _187.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _187.DefaultNodeInfo): _187.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _187.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _187.DefaultNodeInfoOther;
            fromPartial(object: Partial<_187.DefaultNodeInfoOther>): _187.DefaultNodeInfoOther;
            fromAmino(object: _187.DefaultNodeInfoOtherAmino): _187.DefaultNodeInfoOther;
            toAmino(message: _187.DefaultNodeInfoOther): _187.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _187.DefaultNodeInfoOtherAminoMsg): _187.DefaultNodeInfoOther;
            fromProtoMsg(message: _187.DefaultNodeInfoOtherProtoMsg): _187.DefaultNodeInfoOther;
            toProto(message: _187.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _187.DefaultNodeInfoOther): _187.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _192.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _192.ValidatorSet;
            fromPartial(object: Partial<_192.ValidatorSet>): _192.ValidatorSet;
            fromAmino(object: _192.ValidatorSetAmino): _192.ValidatorSet;
            toAmino(message: _192.ValidatorSet): _192.ValidatorSetAmino;
            fromAminoMsg(object: _192.ValidatorSetAminoMsg): _192.ValidatorSet;
            fromProtoMsg(message: _192.ValidatorSetProtoMsg): _192.ValidatorSet;
            toProto(message: _192.ValidatorSet): Uint8Array;
            toProtoMsg(message: _192.ValidatorSet): _192.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _192.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _192.Validator;
            fromPartial(object: Partial<_192.Validator>): _192.Validator;
            fromAmino(object: _192.ValidatorAmino): _192.Validator;
            toAmino(message: _192.Validator): _192.ValidatorAmino;
            fromAminoMsg(object: _192.ValidatorAminoMsg): _192.Validator;
            fromProtoMsg(message: _192.ValidatorProtoMsg): _192.Validator;
            toProto(message: _192.Validator): Uint8Array;
            toProtoMsg(message: _192.Validator): _192.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _192.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _192.SimpleValidator;
            fromPartial(object: Partial<_192.SimpleValidator>): _192.SimpleValidator;
            fromAmino(object: _192.SimpleValidatorAmino): _192.SimpleValidator;
            toAmino(message: _192.SimpleValidator): _192.SimpleValidatorAmino;
            fromAminoMsg(object: _192.SimpleValidatorAminoMsg): _192.SimpleValidator;
            fromProtoMsg(message: _192.SimpleValidatorProtoMsg): _192.SimpleValidator;
            toProto(message: _192.SimpleValidator): Uint8Array;
            toProtoMsg(message: _192.SimpleValidator): _192.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _191.BlockIDFlag;
        blockIDFlagToJSON(object: _191.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _191.SignedMsgType;
        signedMsgTypeToJSON(object: _191.SignedMsgType): string;
        BlockIDFlag: typeof _191.BlockIDFlag;
        BlockIDFlagSDKType: typeof _191.BlockIDFlag;
        BlockIDFlagAmino: typeof _191.BlockIDFlag;
        SignedMsgType: typeof _191.SignedMsgType;
        SignedMsgTypeSDKType: typeof _191.SignedMsgType;
        SignedMsgTypeAmino: typeof _191.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _191.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.PartSetHeader;
            fromPartial(object: Partial<_191.PartSetHeader>): _191.PartSetHeader;
            fromAmino(object: _191.PartSetHeaderAmino): _191.PartSetHeader;
            toAmino(message: _191.PartSetHeader): _191.PartSetHeaderAmino;
            fromAminoMsg(object: _191.PartSetHeaderAminoMsg): _191.PartSetHeader;
            fromProtoMsg(message: _191.PartSetHeaderProtoMsg): _191.PartSetHeader;
            toProto(message: _191.PartSetHeader): Uint8Array;
            toProtoMsg(message: _191.PartSetHeader): _191.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _191.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Part;
            fromPartial(object: Partial<_191.Part>): _191.Part;
            fromAmino(object: _191.PartAmino): _191.Part;
            toAmino(message: _191.Part): _191.PartAmino;
            fromAminoMsg(object: _191.PartAminoMsg): _191.Part;
            fromProtoMsg(message: _191.PartProtoMsg): _191.Part;
            toProto(message: _191.Part): Uint8Array;
            toProtoMsg(message: _191.Part): _191.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _191.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.BlockID;
            fromPartial(object: Partial<_191.BlockID>): _191.BlockID;
            fromAmino(object: _191.BlockIDAmino): _191.BlockID;
            toAmino(message: _191.BlockID): _191.BlockIDAmino;
            fromAminoMsg(object: _191.BlockIDAminoMsg): _191.BlockID;
            fromProtoMsg(message: _191.BlockIDProtoMsg): _191.BlockID;
            toProto(message: _191.BlockID): Uint8Array;
            toProtoMsg(message: _191.BlockID): _191.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _191.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Header;
            fromPartial(object: Partial<_191.Header>): _191.Header;
            fromAmino(object: _191.HeaderAmino): _191.Header;
            toAmino(message: _191.Header): _191.HeaderAmino;
            fromAminoMsg(object: _191.HeaderAminoMsg): _191.Header;
            fromProtoMsg(message: _191.HeaderProtoMsg): _191.Header;
            toProto(message: _191.Header): Uint8Array;
            toProtoMsg(message: _191.Header): _191.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _191.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Data;
            fromPartial(object: Partial<_191.Data>): _191.Data;
            fromAmino(object: _191.DataAmino): _191.Data;
            toAmino(message: _191.Data): _191.DataAmino;
            fromAminoMsg(object: _191.DataAminoMsg): _191.Data;
            fromProtoMsg(message: _191.DataProtoMsg): _191.Data;
            toProto(message: _191.Data): Uint8Array;
            toProtoMsg(message: _191.Data): _191.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _191.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Vote;
            fromPartial(object: Partial<_191.Vote>): _191.Vote;
            fromAmino(object: _191.VoteAmino): _191.Vote;
            toAmino(message: _191.Vote): _191.VoteAmino;
            fromAminoMsg(object: _191.VoteAminoMsg): _191.Vote;
            fromProtoMsg(message: _191.VoteProtoMsg): _191.Vote;
            toProto(message: _191.Vote): Uint8Array;
            toProtoMsg(message: _191.Vote): _191.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _191.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Commit;
            fromPartial(object: Partial<_191.Commit>): _191.Commit;
            fromAmino(object: _191.CommitAmino): _191.Commit;
            toAmino(message: _191.Commit): _191.CommitAmino;
            fromAminoMsg(object: _191.CommitAminoMsg): _191.Commit;
            fromProtoMsg(message: _191.CommitProtoMsg): _191.Commit;
            toProto(message: _191.Commit): Uint8Array;
            toProtoMsg(message: _191.Commit): _191.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _191.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.CommitSig;
            fromPartial(object: Partial<_191.CommitSig>): _191.CommitSig;
            fromAmino(object: _191.CommitSigAmino): _191.CommitSig;
            toAmino(message: _191.CommitSig): _191.CommitSigAmino;
            fromAminoMsg(object: _191.CommitSigAminoMsg): _191.CommitSig;
            fromProtoMsg(message: _191.CommitSigProtoMsg): _191.CommitSig;
            toProto(message: _191.CommitSig): Uint8Array;
            toProtoMsg(message: _191.CommitSig): _191.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _191.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.Proposal;
            fromPartial(object: Partial<_191.Proposal>): _191.Proposal;
            fromAmino(object: _191.ProposalAmino): _191.Proposal;
            toAmino(message: _191.Proposal): _191.ProposalAmino;
            fromAminoMsg(object: _191.ProposalAminoMsg): _191.Proposal;
            fromProtoMsg(message: _191.ProposalProtoMsg): _191.Proposal;
            toProto(message: _191.Proposal): Uint8Array;
            toProtoMsg(message: _191.Proposal): _191.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _191.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.SignedHeader;
            fromPartial(object: Partial<_191.SignedHeader>): _191.SignedHeader;
            fromAmino(object: _191.SignedHeaderAmino): _191.SignedHeader;
            toAmino(message: _191.SignedHeader): _191.SignedHeaderAmino;
            fromAminoMsg(object: _191.SignedHeaderAminoMsg): _191.SignedHeader;
            fromProtoMsg(message: _191.SignedHeaderProtoMsg): _191.SignedHeader;
            toProto(message: _191.SignedHeader): Uint8Array;
            toProtoMsg(message: _191.SignedHeader): _191.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _191.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.LightBlock;
            fromPartial(object: Partial<_191.LightBlock>): _191.LightBlock;
            fromAmino(object: _191.LightBlockAmino): _191.LightBlock;
            toAmino(message: _191.LightBlock): _191.LightBlockAmino;
            fromAminoMsg(object: _191.LightBlockAminoMsg): _191.LightBlock;
            fromProtoMsg(message: _191.LightBlockProtoMsg): _191.LightBlock;
            toProto(message: _191.LightBlock): Uint8Array;
            toProtoMsg(message: _191.LightBlock): _191.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _191.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.BlockMeta;
            fromPartial(object: Partial<_191.BlockMeta>): _191.BlockMeta;
            fromAmino(object: _191.BlockMetaAmino): _191.BlockMeta;
            toAmino(message: _191.BlockMeta): _191.BlockMetaAmino;
            fromAminoMsg(object: _191.BlockMetaAminoMsg): _191.BlockMeta;
            fromProtoMsg(message: _191.BlockMetaProtoMsg): _191.BlockMeta;
            toProto(message: _191.BlockMeta): Uint8Array;
            toProtoMsg(message: _191.BlockMeta): _191.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _191.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _191.TxProof;
            fromPartial(object: Partial<_191.TxProof>): _191.TxProof;
            fromAmino(object: _191.TxProofAmino): _191.TxProof;
            toAmino(message: _191.TxProof): _191.TxProofAmino;
            fromAminoMsg(object: _191.TxProofAminoMsg): _191.TxProof;
            fromProtoMsg(message: _191.TxProofProtoMsg): _191.TxProof;
            toProto(message: _191.TxProof): Uint8Array;
            toProtoMsg(message: _191.TxProof): _191.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _190.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.ConsensusParams;
            fromPartial(object: Partial<_190.ConsensusParams>): _190.ConsensusParams;
            fromAmino(object: _190.ConsensusParamsAmino): _190.ConsensusParams;
            toAmino(message: _190.ConsensusParams): _190.ConsensusParamsAmino;
            fromAminoMsg(object: _190.ConsensusParamsAminoMsg): _190.ConsensusParams;
            fromProtoMsg(message: _190.ConsensusParamsProtoMsg): _190.ConsensusParams;
            toProto(message: _190.ConsensusParams): Uint8Array;
            toProtoMsg(message: _190.ConsensusParams): _190.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _190.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.BlockParams;
            fromPartial(object: Partial<_190.BlockParams>): _190.BlockParams;
            fromAmino(object: _190.BlockParamsAmino): _190.BlockParams;
            toAmino(message: _190.BlockParams): _190.BlockParamsAmino;
            fromAminoMsg(object: _190.BlockParamsAminoMsg): _190.BlockParams;
            fromProtoMsg(message: _190.BlockParamsProtoMsg): _190.BlockParams;
            toProto(message: _190.BlockParams): Uint8Array;
            toProtoMsg(message: _190.BlockParams): _190.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _190.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.EvidenceParams;
            fromPartial(object: Partial<_190.EvidenceParams>): _190.EvidenceParams;
            fromAmino(object: _190.EvidenceParamsAmino): _190.EvidenceParams;
            toAmino(message: _190.EvidenceParams): _190.EvidenceParamsAmino;
            fromAminoMsg(object: _190.EvidenceParamsAminoMsg): _190.EvidenceParams;
            fromProtoMsg(message: _190.EvidenceParamsProtoMsg): _190.EvidenceParams;
            toProto(message: _190.EvidenceParams): Uint8Array;
            toProtoMsg(message: _190.EvidenceParams): _190.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _190.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.ValidatorParams;
            fromPartial(object: Partial<_190.ValidatorParams>): _190.ValidatorParams;
            fromAmino(object: _190.ValidatorParamsAmino): _190.ValidatorParams;
            toAmino(message: _190.ValidatorParams): _190.ValidatorParamsAmino;
            fromAminoMsg(object: _190.ValidatorParamsAminoMsg): _190.ValidatorParams;
            fromProtoMsg(message: _190.ValidatorParamsProtoMsg): _190.ValidatorParams;
            toProto(message: _190.ValidatorParams): Uint8Array;
            toProtoMsg(message: _190.ValidatorParams): _190.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _190.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.VersionParams;
            fromPartial(object: Partial<_190.VersionParams>): _190.VersionParams;
            fromAmino(object: _190.VersionParamsAmino): _190.VersionParams;
            toAmino(message: _190.VersionParams): _190.VersionParamsAmino;
            fromAminoMsg(object: _190.VersionParamsAminoMsg): _190.VersionParams;
            fromProtoMsg(message: _190.VersionParamsProtoMsg): _190.VersionParams;
            toProto(message: _190.VersionParams): Uint8Array;
            toProtoMsg(message: _190.VersionParams): _190.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _190.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _190.HashedParams;
            fromPartial(object: Partial<_190.HashedParams>): _190.HashedParams;
            fromAmino(object: _190.HashedParamsAmino): _190.HashedParams;
            toAmino(message: _190.HashedParams): _190.HashedParamsAmino;
            fromAminoMsg(object: _190.HashedParamsAminoMsg): _190.HashedParams;
            fromProtoMsg(message: _190.HashedParamsProtoMsg): _190.HashedParams;
            toProto(message: _190.HashedParams): Uint8Array;
            toProtoMsg(message: _190.HashedParams): _190.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _189.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _189.Evidence;
            fromPartial(object: Partial<_189.Evidence>): _189.Evidence;
            fromAmino(object: _189.EvidenceAmino): _189.Evidence;
            toAmino(message: _189.Evidence): _189.EvidenceAmino;
            fromAminoMsg(object: _189.EvidenceAminoMsg): _189.Evidence;
            fromProtoMsg(message: _189.EvidenceProtoMsg): _189.Evidence;
            toProto(message: _189.Evidence): Uint8Array;
            toProtoMsg(message: _189.Evidence): _189.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _189.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _189.DuplicateVoteEvidence;
            fromPartial(object: Partial<_189.DuplicateVoteEvidence>): _189.DuplicateVoteEvidence;
            fromAmino(object: _189.DuplicateVoteEvidenceAmino): _189.DuplicateVoteEvidence;
            toAmino(message: _189.DuplicateVoteEvidence): _189.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _189.DuplicateVoteEvidenceAminoMsg): _189.DuplicateVoteEvidence;
            fromProtoMsg(message: _189.DuplicateVoteEvidenceProtoMsg): _189.DuplicateVoteEvidence;
            toProto(message: _189.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _189.DuplicateVoteEvidence): _189.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _189.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _189.LightClientAttackEvidence;
            fromPartial(object: Partial<_189.LightClientAttackEvidence>): _189.LightClientAttackEvidence;
            fromAmino(object: _189.LightClientAttackEvidenceAmino): _189.LightClientAttackEvidence;
            toAmino(message: _189.LightClientAttackEvidence): _189.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _189.LightClientAttackEvidenceAminoMsg): _189.LightClientAttackEvidence;
            fromProtoMsg(message: _189.LightClientAttackEvidenceProtoMsg): _189.LightClientAttackEvidence;
            toProto(message: _189.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _189.LightClientAttackEvidence): _189.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _189.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _189.EvidenceList;
            fromPartial(object: Partial<_189.EvidenceList>): _189.EvidenceList;
            fromAmino(object: _189.EvidenceListAmino): _189.EvidenceList;
            toAmino(message: _189.EvidenceList): _189.EvidenceListAmino;
            fromAminoMsg(object: _189.EvidenceListAminoMsg): _189.EvidenceList;
            fromProtoMsg(message: _189.EvidenceListProtoMsg): _189.EvidenceList;
            toProto(message: _189.EvidenceList): Uint8Array;
            toProtoMsg(message: _189.EvidenceList): _189.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _188.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _188.Block;
            fromPartial(object: Partial<_188.Block>): _188.Block;
            fromAmino(object: _188.BlockAmino): _188.Block;
            toAmino(message: _188.Block): _188.BlockAmino;
            fromAminoMsg(object: _188.BlockAminoMsg): _188.Block;
            fromProtoMsg(message: _188.BlockProtoMsg): _188.Block;
            toProto(message: _188.Block): Uint8Array;
            toProtoMsg(message: _188.Block): _188.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _193.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _193.App;
            fromPartial(object: Partial<_193.App>): _193.App;
            fromAmino(object: _193.AppAmino): _193.App;
            toAmino(message: _193.App): _193.AppAmino;
            fromAminoMsg(object: _193.AppAminoMsg): _193.App;
            fromProtoMsg(message: _193.AppProtoMsg): _193.App;
            toProto(message: _193.App): Uint8Array;
            toProtoMsg(message: _193.App): _193.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _193.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _193.Consensus;
            fromPartial(object: Partial<_193.Consensus>): _193.Consensus;
            fromAmino(object: _193.ConsensusAmino): _193.Consensus;
            toAmino(message: _193.Consensus): _193.ConsensusAmino;
            fromAminoMsg(object: _193.ConsensusAminoMsg): _193.Consensus;
            fromProtoMsg(message: _193.ConsensusProtoMsg): _193.Consensus;
            toProto(message: _193.Consensus): Uint8Array;
            toProtoMsg(message: _193.Consensus): _193.ConsensusProtoMsg;
        };
    };
}
