import * as _131 from "./api/http";
import * as _132 from "./protobuf/descriptor";
import * as _133 from "./protobuf/any";
import * as _134 from "./protobuf/timestamp";
import * as _135 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _131.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _131.Http;
            fromPartial(object: Partial<_131.Http>): _131.Http;
            fromAmino(object: _131.HttpAmino): _131.Http;
            toAmino(message: _131.Http): _131.HttpAmino;
            fromAminoMsg(object: _131.HttpAminoMsg): _131.Http;
            fromProtoMsg(message: _131.HttpProtoMsg): _131.Http;
            toProto(message: _131.Http): Uint8Array;
            toProtoMsg(message: _131.Http): _131.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _131.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _131.HttpRule;
            fromPartial(object: Partial<_131.HttpRule>): _131.HttpRule;
            fromAmino(object: _131.HttpRuleAmino): _131.HttpRule;
            toAmino(message: _131.HttpRule): _131.HttpRuleAmino;
            fromAminoMsg(object: _131.HttpRuleAminoMsg): _131.HttpRule;
            fromProtoMsg(message: _131.HttpRuleProtoMsg): _131.HttpRule;
            toProto(message: _131.HttpRule): Uint8Array;
            toProtoMsg(message: _131.HttpRule): _131.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _131.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _131.CustomHttpPattern;
            fromPartial(object: Partial<_131.CustomHttpPattern>): _131.CustomHttpPattern;
            fromAmino(object: _131.CustomHttpPatternAmino): _131.CustomHttpPattern;
            toAmino(message: _131.CustomHttpPattern): _131.CustomHttpPatternAmino;
            fromAminoMsg(object: _131.CustomHttpPatternAminoMsg): _131.CustomHttpPattern;
            fromProtoMsg(message: _131.CustomHttpPatternProtoMsg): _131.CustomHttpPattern;
            toProto(message: _131.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _131.CustomHttpPattern): _131.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _135.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _135.Duration;
            fromPartial(object: Partial<_135.Duration>): _135.Duration;
            fromAmino(object: string): _135.Duration;
            toAmino(message: _135.Duration): string;
            fromAminoMsg(object: _135.DurationAminoMsg): _135.Duration;
            fromProtoMsg(message: _135.DurationProtoMsg): _135.Duration;
            toProto(message: _135.Duration): Uint8Array;
            toProtoMsg(message: _135.Duration): _135.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _134.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _134.Timestamp;
            fromPartial(object: Partial<_134.Timestamp>): _134.Timestamp;
            fromAmino(object: string): _134.Timestamp;
            toAmino(message: _134.Timestamp): string;
            fromAminoMsg(object: _134.TimestampAminoMsg): _134.Timestamp;
            fromProtoMsg(message: _134.TimestampProtoMsg): _134.Timestamp;
            toProto(message: _134.Timestamp): Uint8Array;
            toProtoMsg(message: _134.Timestamp): _134.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _133.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _133.Any;
            fromPartial(object: Partial<_133.Any>): _133.Any;
            fromAmino(object: _133.AnyAmino): _133.Any;
            toAmino(message: _133.Any): _133.AnyAmino;
            fromAminoMsg(object: _133.AnyAminoMsg): _133.Any;
            fromProtoMsg(message: _133.AnyProtoMsg): _133.Any;
            toProto(message: _133.Any): Uint8Array;
            toProtoMsg(message: _133.Any): _133.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _132.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _132.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _132.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _132.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _132.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _132.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _132.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _132.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _132.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _132.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _132.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _132.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _132.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _132.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _132.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _132.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _132.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _132.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _132.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _132.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _132.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _132.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _132.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _132.FieldOptions_CType;
        FieldOptions_JSType: typeof _132.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _132.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _132.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _132.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _132.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _132.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _132.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.FileDescriptorSet;
            fromPartial(object: Partial<_132.FileDescriptorSet>): _132.FileDescriptorSet;
            fromAmino(object: _132.FileDescriptorSetAmino): _132.FileDescriptorSet;
            toAmino(message: _132.FileDescriptorSet): _132.FileDescriptorSetAmino;
            fromAminoMsg(object: _132.FileDescriptorSetAminoMsg): _132.FileDescriptorSet;
            fromProtoMsg(message: _132.FileDescriptorSetProtoMsg): _132.FileDescriptorSet;
            toProto(message: _132.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _132.FileDescriptorSet): _132.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _132.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.FileDescriptorProto;
            fromPartial(object: Partial<_132.FileDescriptorProto>): _132.FileDescriptorProto;
            fromAmino(object: _132.FileDescriptorProtoAmino): _132.FileDescriptorProto;
            toAmino(message: _132.FileDescriptorProto): _132.FileDescriptorProtoAmino;
            fromAminoMsg(object: _132.FileDescriptorProtoAminoMsg): _132.FileDescriptorProto;
            fromProtoMsg(message: _132.FileDescriptorProtoProtoMsg): _132.FileDescriptorProto;
            toProto(message: _132.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.FileDescriptorProto): _132.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _132.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.DescriptorProto;
            fromPartial(object: Partial<_132.DescriptorProto>): _132.DescriptorProto;
            fromAmino(object: _132.DescriptorProtoAmino): _132.DescriptorProto;
            toAmino(message: _132.DescriptorProto): _132.DescriptorProtoAmino;
            fromAminoMsg(object: _132.DescriptorProtoAminoMsg): _132.DescriptorProto;
            fromProtoMsg(message: _132.DescriptorProtoProtoMsg): _132.DescriptorProto;
            toProto(message: _132.DescriptorProto): Uint8Array;
            toProtoMsg(message: _132.DescriptorProto): _132.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _132.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_132.DescriptorProto_ExtensionRange>): _132.DescriptorProto_ExtensionRange;
            fromAmino(object: _132.DescriptorProto_ExtensionRangeAmino): _132.DescriptorProto_ExtensionRange;
            toAmino(message: _132.DescriptorProto_ExtensionRange): _132.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _132.DescriptorProto_ExtensionRangeAminoMsg): _132.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _132.DescriptorProto_ExtensionRangeProtoMsg): _132.DescriptorProto_ExtensionRange;
            toProto(message: _132.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _132.DescriptorProto_ExtensionRange): _132.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _132.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_132.DescriptorProto_ReservedRange>): _132.DescriptorProto_ReservedRange;
            fromAmino(object: _132.DescriptorProto_ReservedRangeAmino): _132.DescriptorProto_ReservedRange;
            toAmino(message: _132.DescriptorProto_ReservedRange): _132.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _132.DescriptorProto_ReservedRangeAminoMsg): _132.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _132.DescriptorProto_ReservedRangeProtoMsg): _132.DescriptorProto_ReservedRange;
            toProto(message: _132.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _132.DescriptorProto_ReservedRange): _132.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _132.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.ExtensionRangeOptions;
            fromPartial(object: Partial<_132.ExtensionRangeOptions>): _132.ExtensionRangeOptions;
            fromAmino(object: _132.ExtensionRangeOptionsAmino): _132.ExtensionRangeOptions;
            toAmino(message: _132.ExtensionRangeOptions): _132.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _132.ExtensionRangeOptionsAminoMsg): _132.ExtensionRangeOptions;
            fromProtoMsg(message: _132.ExtensionRangeOptionsProtoMsg): _132.ExtensionRangeOptions;
            toProto(message: _132.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _132.ExtensionRangeOptions): _132.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _132.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.FieldDescriptorProto;
            fromPartial(object: Partial<_132.FieldDescriptorProto>): _132.FieldDescriptorProto;
            fromAmino(object: _132.FieldDescriptorProtoAmino): _132.FieldDescriptorProto;
            toAmino(message: _132.FieldDescriptorProto): _132.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _132.FieldDescriptorProtoAminoMsg): _132.FieldDescriptorProto;
            fromProtoMsg(message: _132.FieldDescriptorProtoProtoMsg): _132.FieldDescriptorProto;
            toProto(message: _132.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.FieldDescriptorProto): _132.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _132.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.OneofDescriptorProto;
            fromPartial(object: Partial<_132.OneofDescriptorProto>): _132.OneofDescriptorProto;
            fromAmino(object: _132.OneofDescriptorProtoAmino): _132.OneofDescriptorProto;
            toAmino(message: _132.OneofDescriptorProto): _132.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _132.OneofDescriptorProtoAminoMsg): _132.OneofDescriptorProto;
            fromProtoMsg(message: _132.OneofDescriptorProtoProtoMsg): _132.OneofDescriptorProto;
            toProto(message: _132.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.OneofDescriptorProto): _132.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _132.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.EnumDescriptorProto;
            fromPartial(object: Partial<_132.EnumDescriptorProto>): _132.EnumDescriptorProto;
            fromAmino(object: _132.EnumDescriptorProtoAmino): _132.EnumDescriptorProto;
            toAmino(message: _132.EnumDescriptorProto): _132.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _132.EnumDescriptorProtoAminoMsg): _132.EnumDescriptorProto;
            fromProtoMsg(message: _132.EnumDescriptorProtoProtoMsg): _132.EnumDescriptorProto;
            toProto(message: _132.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.EnumDescriptorProto): _132.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _132.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_132.EnumDescriptorProto_EnumReservedRange>): _132.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _132.EnumDescriptorProto_EnumReservedRangeAmino): _132.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _132.EnumDescriptorProto_EnumReservedRange): _132.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _132.EnumDescriptorProto_EnumReservedRangeAminoMsg): _132.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _132.EnumDescriptorProto_EnumReservedRangeProtoMsg): _132.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _132.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _132.EnumDescriptorProto_EnumReservedRange): _132.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _132.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.EnumValueDescriptorProto;
            fromPartial(object: Partial<_132.EnumValueDescriptorProto>): _132.EnumValueDescriptorProto;
            fromAmino(object: _132.EnumValueDescriptorProtoAmino): _132.EnumValueDescriptorProto;
            toAmino(message: _132.EnumValueDescriptorProto): _132.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _132.EnumValueDescriptorProtoAminoMsg): _132.EnumValueDescriptorProto;
            fromProtoMsg(message: _132.EnumValueDescriptorProtoProtoMsg): _132.EnumValueDescriptorProto;
            toProto(message: _132.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.EnumValueDescriptorProto): _132.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _132.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.ServiceDescriptorProto;
            fromPartial(object: Partial<_132.ServiceDescriptorProto>): _132.ServiceDescriptorProto;
            fromAmino(object: _132.ServiceDescriptorProtoAmino): _132.ServiceDescriptorProto;
            toAmino(message: _132.ServiceDescriptorProto): _132.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _132.ServiceDescriptorProtoAminoMsg): _132.ServiceDescriptorProto;
            fromProtoMsg(message: _132.ServiceDescriptorProtoProtoMsg): _132.ServiceDescriptorProto;
            toProto(message: _132.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.ServiceDescriptorProto): _132.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _132.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.MethodDescriptorProto;
            fromPartial(object: Partial<_132.MethodDescriptorProto>): _132.MethodDescriptorProto;
            fromAmino(object: _132.MethodDescriptorProtoAmino): _132.MethodDescriptorProto;
            toAmino(message: _132.MethodDescriptorProto): _132.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _132.MethodDescriptorProtoAminoMsg): _132.MethodDescriptorProto;
            fromProtoMsg(message: _132.MethodDescriptorProtoProtoMsg): _132.MethodDescriptorProto;
            toProto(message: _132.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _132.MethodDescriptorProto): _132.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _132.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.FileOptions;
            fromPartial(object: Partial<_132.FileOptions>): _132.FileOptions;
            fromAmino(object: _132.FileOptionsAmino): _132.FileOptions;
            toAmino(message: _132.FileOptions): _132.FileOptionsAmino;
            fromAminoMsg(object: _132.FileOptionsAminoMsg): _132.FileOptions;
            fromProtoMsg(message: _132.FileOptionsProtoMsg): _132.FileOptions;
            toProto(message: _132.FileOptions): Uint8Array;
            toProtoMsg(message: _132.FileOptions): _132.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _132.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.MessageOptions;
            fromPartial(object: Partial<_132.MessageOptions>): _132.MessageOptions;
            fromAmino(object: _132.MessageOptionsAmino): _132.MessageOptions;
            toAmino(message: _132.MessageOptions): _132.MessageOptionsAmino;
            fromAminoMsg(object: _132.MessageOptionsAminoMsg): _132.MessageOptions;
            fromProtoMsg(message: _132.MessageOptionsProtoMsg): _132.MessageOptions;
            toProto(message: _132.MessageOptions): Uint8Array;
            toProtoMsg(message: _132.MessageOptions): _132.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _132.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.FieldOptions;
            fromPartial(object: Partial<_132.FieldOptions>): _132.FieldOptions;
            fromAmino(object: _132.FieldOptionsAmino): _132.FieldOptions;
            toAmino(message: _132.FieldOptions): _132.FieldOptionsAmino;
            fromAminoMsg(object: _132.FieldOptionsAminoMsg): _132.FieldOptions;
            fromProtoMsg(message: _132.FieldOptionsProtoMsg): _132.FieldOptions;
            toProto(message: _132.FieldOptions): Uint8Array;
            toProtoMsg(message: _132.FieldOptions): _132.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _132.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.OneofOptions;
            fromPartial(object: Partial<_132.OneofOptions>): _132.OneofOptions;
            fromAmino(object: _132.OneofOptionsAmino): _132.OneofOptions;
            toAmino(message: _132.OneofOptions): _132.OneofOptionsAmino;
            fromAminoMsg(object: _132.OneofOptionsAminoMsg): _132.OneofOptions;
            fromProtoMsg(message: _132.OneofOptionsProtoMsg): _132.OneofOptions;
            toProto(message: _132.OneofOptions): Uint8Array;
            toProtoMsg(message: _132.OneofOptions): _132.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _132.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.EnumOptions;
            fromPartial(object: Partial<_132.EnumOptions>): _132.EnumOptions;
            fromAmino(object: _132.EnumOptionsAmino): _132.EnumOptions;
            toAmino(message: _132.EnumOptions): _132.EnumOptionsAmino;
            fromAminoMsg(object: _132.EnumOptionsAminoMsg): _132.EnumOptions;
            fromProtoMsg(message: _132.EnumOptionsProtoMsg): _132.EnumOptions;
            toProto(message: _132.EnumOptions): Uint8Array;
            toProtoMsg(message: _132.EnumOptions): _132.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _132.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.EnumValueOptions;
            fromPartial(object: Partial<_132.EnumValueOptions>): _132.EnumValueOptions;
            fromAmino(object: _132.EnumValueOptionsAmino): _132.EnumValueOptions;
            toAmino(message: _132.EnumValueOptions): _132.EnumValueOptionsAmino;
            fromAminoMsg(object: _132.EnumValueOptionsAminoMsg): _132.EnumValueOptions;
            fromProtoMsg(message: _132.EnumValueOptionsProtoMsg): _132.EnumValueOptions;
            toProto(message: _132.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _132.EnumValueOptions): _132.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _132.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.ServiceOptions;
            fromPartial(object: Partial<_132.ServiceOptions>): _132.ServiceOptions;
            fromAmino(object: _132.ServiceOptionsAmino): _132.ServiceOptions;
            toAmino(message: _132.ServiceOptions): _132.ServiceOptionsAmino;
            fromAminoMsg(object: _132.ServiceOptionsAminoMsg): _132.ServiceOptions;
            fromProtoMsg(message: _132.ServiceOptionsProtoMsg): _132.ServiceOptions;
            toProto(message: _132.ServiceOptions): Uint8Array;
            toProtoMsg(message: _132.ServiceOptions): _132.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _132.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.MethodOptions;
            fromPartial(object: Partial<_132.MethodOptions>): _132.MethodOptions;
            fromAmino(object: _132.MethodOptionsAmino): _132.MethodOptions;
            toAmino(message: _132.MethodOptions): _132.MethodOptionsAmino;
            fromAminoMsg(object: _132.MethodOptionsAminoMsg): _132.MethodOptions;
            fromProtoMsg(message: _132.MethodOptionsProtoMsg): _132.MethodOptions;
            toProto(message: _132.MethodOptions): Uint8Array;
            toProtoMsg(message: _132.MethodOptions): _132.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _132.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.UninterpretedOption;
            fromPartial(object: Partial<_132.UninterpretedOption>): _132.UninterpretedOption;
            fromAmino(object: _132.UninterpretedOptionAmino): _132.UninterpretedOption;
            toAmino(message: _132.UninterpretedOption): _132.UninterpretedOptionAmino;
            fromAminoMsg(object: _132.UninterpretedOptionAminoMsg): _132.UninterpretedOption;
            fromProtoMsg(message: _132.UninterpretedOptionProtoMsg): _132.UninterpretedOption;
            toProto(message: _132.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _132.UninterpretedOption): _132.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _132.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_132.UninterpretedOption_NamePart>): _132.UninterpretedOption_NamePart;
            fromAmino(object: _132.UninterpretedOption_NamePartAmino): _132.UninterpretedOption_NamePart;
            toAmino(message: _132.UninterpretedOption_NamePart): _132.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _132.UninterpretedOption_NamePartAminoMsg): _132.UninterpretedOption_NamePart;
            fromProtoMsg(message: _132.UninterpretedOption_NamePartProtoMsg): _132.UninterpretedOption_NamePart;
            toProto(message: _132.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _132.UninterpretedOption_NamePart): _132.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _132.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.SourceCodeInfo;
            fromPartial(object: Partial<_132.SourceCodeInfo>): _132.SourceCodeInfo;
            fromAmino(object: _132.SourceCodeInfoAmino): _132.SourceCodeInfo;
            toAmino(message: _132.SourceCodeInfo): _132.SourceCodeInfoAmino;
            fromAminoMsg(object: _132.SourceCodeInfoAminoMsg): _132.SourceCodeInfo;
            fromProtoMsg(message: _132.SourceCodeInfoProtoMsg): _132.SourceCodeInfo;
            toProto(message: _132.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _132.SourceCodeInfo): _132.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _132.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.SourceCodeInfo_Location;
            fromPartial(object: Partial<_132.SourceCodeInfo_Location>): _132.SourceCodeInfo_Location;
            fromAmino(object: _132.SourceCodeInfo_LocationAmino): _132.SourceCodeInfo_Location;
            toAmino(message: _132.SourceCodeInfo_Location): _132.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _132.SourceCodeInfo_LocationAminoMsg): _132.SourceCodeInfo_Location;
            fromProtoMsg(message: _132.SourceCodeInfo_LocationProtoMsg): _132.SourceCodeInfo_Location;
            toProto(message: _132.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _132.SourceCodeInfo_Location): _132.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _132.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.GeneratedCodeInfo;
            fromPartial(object: Partial<_132.GeneratedCodeInfo>): _132.GeneratedCodeInfo;
            fromAmino(object: _132.GeneratedCodeInfoAmino): _132.GeneratedCodeInfo;
            toAmino(message: _132.GeneratedCodeInfo): _132.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _132.GeneratedCodeInfoAminoMsg): _132.GeneratedCodeInfo;
            fromProtoMsg(message: _132.GeneratedCodeInfoProtoMsg): _132.GeneratedCodeInfo;
            toProto(message: _132.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _132.GeneratedCodeInfo): _132.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _132.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _132.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_132.GeneratedCodeInfo_Annotation>): _132.GeneratedCodeInfo_Annotation;
            fromAmino(object: _132.GeneratedCodeInfo_AnnotationAmino): _132.GeneratedCodeInfo_Annotation;
            toAmino(message: _132.GeneratedCodeInfo_Annotation): _132.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _132.GeneratedCodeInfo_AnnotationAminoMsg): _132.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _132.GeneratedCodeInfo_AnnotationProtoMsg): _132.GeneratedCodeInfo_Annotation;
            toProto(message: _132.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _132.GeneratedCodeInfo_Annotation): _132.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
