import * as _78 from "./api/http";
import * as _79 from "./api/httpbody";
import * as _80 from "./protobuf/descriptor";
import * as _81 from "./protobuf/any";
import * as _82 from "./protobuf/timestamp";
import * as _83 from "./protobuf/duration";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _79.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _79.HttpBody;
            fromPartial(object: Partial<_79.HttpBody>): _79.HttpBody;
            fromAmino(object: _79.HttpBodyAmino): _79.HttpBody;
            toAmino(message: _79.HttpBody): _79.HttpBodyAmino;
            fromAminoMsg(object: _79.HttpBodyAminoMsg): _79.HttpBody;
            fromProtoMsg(message: _79.HttpBodyProtoMsg): _79.HttpBody;
            toProto(message: _79.HttpBody): Uint8Array;
            toProtoMsg(message: _79.HttpBody): _79.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _78.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _78.Http;
            fromPartial(object: Partial<_78.Http>): _78.Http;
            fromAmino(object: _78.HttpAmino): _78.Http;
            toAmino(message: _78.Http): _78.HttpAmino;
            fromAminoMsg(object: _78.HttpAminoMsg): _78.Http;
            fromProtoMsg(message: _78.HttpProtoMsg): _78.Http;
            toProto(message: _78.Http): Uint8Array;
            toProtoMsg(message: _78.Http): _78.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _78.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _78.HttpRule;
            fromPartial(object: Partial<_78.HttpRule>): _78.HttpRule;
            fromAmino(object: _78.HttpRuleAmino): _78.HttpRule;
            toAmino(message: _78.HttpRule): _78.HttpRuleAmino;
            fromAminoMsg(object: _78.HttpRuleAminoMsg): _78.HttpRule;
            fromProtoMsg(message: _78.HttpRuleProtoMsg): _78.HttpRule;
            toProto(message: _78.HttpRule): Uint8Array;
            toProtoMsg(message: _78.HttpRule): _78.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _78.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _78.CustomHttpPattern;
            fromPartial(object: Partial<_78.CustomHttpPattern>): _78.CustomHttpPattern;
            fromAmino(object: _78.CustomHttpPatternAmino): _78.CustomHttpPattern;
            toAmino(message: _78.CustomHttpPattern): _78.CustomHttpPatternAmino;
            fromAminoMsg(object: _78.CustomHttpPatternAminoMsg): _78.CustomHttpPattern;
            fromProtoMsg(message: _78.CustomHttpPatternProtoMsg): _78.CustomHttpPattern;
            toProto(message: _78.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _78.CustomHttpPattern): _78.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _83.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _83.Duration;
            fromPartial(object: Partial<_83.Duration>): _83.Duration;
            fromAmino(object: string): _83.Duration;
            toAmino(message: _83.Duration): string;
            fromAminoMsg(object: _83.DurationAminoMsg): _83.Duration;
            fromProtoMsg(message: _83.DurationProtoMsg): _83.Duration;
            toProto(message: _83.Duration): Uint8Array;
            toProtoMsg(message: _83.Duration): _83.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _82.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _82.Timestamp;
            fromPartial(object: Partial<_82.Timestamp>): _82.Timestamp;
            fromAmino(object: string): _82.Timestamp;
            toAmino(message: _82.Timestamp): string;
            fromAminoMsg(object: _82.TimestampAminoMsg): _82.Timestamp;
            fromProtoMsg(message: _82.TimestampProtoMsg): _82.Timestamp;
            toProto(message: _82.Timestamp): Uint8Array;
            toProtoMsg(message: _82.Timestamp): _82.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _81.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _81.Any;
            fromPartial(object: Partial<_81.Any>): _81.Any;
            fromAmino(object: _81.AnyAmino): _81.Any;
            toAmino(message: _81.Any): _81.AnyAmino;
            fromAminoMsg(object: _81.AnyAminoMsg): _81.Any;
            fromProtoMsg(message: _81.AnyProtoMsg): _81.Any;
            toProto(message: _81.Any): Uint8Array;
            toProtoMsg(message: _81.Any): _81.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _80.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _80.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _80.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _80.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _80.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _80.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _80.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _80.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _80.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _80.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _80.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _80.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _80.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _80.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _80.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _80.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _80.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _80.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _80.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _80.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _80.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _80.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _80.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _80.FieldOptions_CType;
        FieldOptions_JSType: typeof _80.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _80.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _80.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _80.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _80.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _80.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _80.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.FileDescriptorSet;
            fromPartial(object: Partial<_80.FileDescriptorSet>): _80.FileDescriptorSet;
            fromAmino(object: _80.FileDescriptorSetAmino): _80.FileDescriptorSet;
            toAmino(message: _80.FileDescriptorSet): _80.FileDescriptorSetAmino;
            fromAminoMsg(object: _80.FileDescriptorSetAminoMsg): _80.FileDescriptorSet;
            fromProtoMsg(message: _80.FileDescriptorSetProtoMsg): _80.FileDescriptorSet;
            toProto(message: _80.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _80.FileDescriptorSet): _80.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _80.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.FileDescriptorProto;
            fromPartial(object: Partial<_80.FileDescriptorProto>): _80.FileDescriptorProto;
            fromAmino(object: _80.FileDescriptorProtoAmino): _80.FileDescriptorProto;
            toAmino(message: _80.FileDescriptorProto): _80.FileDescriptorProtoAmino;
            fromAminoMsg(object: _80.FileDescriptorProtoAminoMsg): _80.FileDescriptorProto;
            fromProtoMsg(message: _80.FileDescriptorProtoProtoMsg): _80.FileDescriptorProto;
            toProto(message: _80.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.FileDescriptorProto): _80.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _80.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.DescriptorProto;
            fromPartial(object: Partial<_80.DescriptorProto>): _80.DescriptorProto;
            fromAmino(object: _80.DescriptorProtoAmino): _80.DescriptorProto;
            toAmino(message: _80.DescriptorProto): _80.DescriptorProtoAmino;
            fromAminoMsg(object: _80.DescriptorProtoAminoMsg): _80.DescriptorProto;
            fromProtoMsg(message: _80.DescriptorProtoProtoMsg): _80.DescriptorProto;
            toProto(message: _80.DescriptorProto): Uint8Array;
            toProtoMsg(message: _80.DescriptorProto): _80.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _80.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_80.DescriptorProto_ExtensionRange>): _80.DescriptorProto_ExtensionRange;
            fromAmino(object: _80.DescriptorProto_ExtensionRangeAmino): _80.DescriptorProto_ExtensionRange;
            toAmino(message: _80.DescriptorProto_ExtensionRange): _80.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _80.DescriptorProto_ExtensionRangeAminoMsg): _80.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _80.DescriptorProto_ExtensionRangeProtoMsg): _80.DescriptorProto_ExtensionRange;
            toProto(message: _80.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _80.DescriptorProto_ExtensionRange): _80.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _80.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_80.DescriptorProto_ReservedRange>): _80.DescriptorProto_ReservedRange;
            fromAmino(object: _80.DescriptorProto_ReservedRangeAmino): _80.DescriptorProto_ReservedRange;
            toAmino(message: _80.DescriptorProto_ReservedRange): _80.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _80.DescriptorProto_ReservedRangeAminoMsg): _80.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _80.DescriptorProto_ReservedRangeProtoMsg): _80.DescriptorProto_ReservedRange;
            toProto(message: _80.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _80.DescriptorProto_ReservedRange): _80.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _80.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.ExtensionRangeOptions;
            fromPartial(object: Partial<_80.ExtensionRangeOptions>): _80.ExtensionRangeOptions;
            fromAmino(object: _80.ExtensionRangeOptionsAmino): _80.ExtensionRangeOptions;
            toAmino(message: _80.ExtensionRangeOptions): _80.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _80.ExtensionRangeOptionsAminoMsg): _80.ExtensionRangeOptions;
            fromProtoMsg(message: _80.ExtensionRangeOptionsProtoMsg): _80.ExtensionRangeOptions;
            toProto(message: _80.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _80.ExtensionRangeOptions): _80.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _80.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.FieldDescriptorProto;
            fromPartial(object: Partial<_80.FieldDescriptorProto>): _80.FieldDescriptorProto;
            fromAmino(object: _80.FieldDescriptorProtoAmino): _80.FieldDescriptorProto;
            toAmino(message: _80.FieldDescriptorProto): _80.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _80.FieldDescriptorProtoAminoMsg): _80.FieldDescriptorProto;
            fromProtoMsg(message: _80.FieldDescriptorProtoProtoMsg): _80.FieldDescriptorProto;
            toProto(message: _80.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.FieldDescriptorProto): _80.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _80.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.OneofDescriptorProto;
            fromPartial(object: Partial<_80.OneofDescriptorProto>): _80.OneofDescriptorProto;
            fromAmino(object: _80.OneofDescriptorProtoAmino): _80.OneofDescriptorProto;
            toAmino(message: _80.OneofDescriptorProto): _80.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _80.OneofDescriptorProtoAminoMsg): _80.OneofDescriptorProto;
            fromProtoMsg(message: _80.OneofDescriptorProtoProtoMsg): _80.OneofDescriptorProto;
            toProto(message: _80.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.OneofDescriptorProto): _80.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _80.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.EnumDescriptorProto;
            fromPartial(object: Partial<_80.EnumDescriptorProto>): _80.EnumDescriptorProto;
            fromAmino(object: _80.EnumDescriptorProtoAmino): _80.EnumDescriptorProto;
            toAmino(message: _80.EnumDescriptorProto): _80.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _80.EnumDescriptorProtoAminoMsg): _80.EnumDescriptorProto;
            fromProtoMsg(message: _80.EnumDescriptorProtoProtoMsg): _80.EnumDescriptorProto;
            toProto(message: _80.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.EnumDescriptorProto): _80.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _80.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_80.EnumDescriptorProto_EnumReservedRange>): _80.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _80.EnumDescriptorProto_EnumReservedRangeAmino): _80.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _80.EnumDescriptorProto_EnumReservedRange): _80.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _80.EnumDescriptorProto_EnumReservedRangeAminoMsg): _80.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _80.EnumDescriptorProto_EnumReservedRangeProtoMsg): _80.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _80.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _80.EnumDescriptorProto_EnumReservedRange): _80.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _80.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.EnumValueDescriptorProto;
            fromPartial(object: Partial<_80.EnumValueDescriptorProto>): _80.EnumValueDescriptorProto;
            fromAmino(object: _80.EnumValueDescriptorProtoAmino): _80.EnumValueDescriptorProto;
            toAmino(message: _80.EnumValueDescriptorProto): _80.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _80.EnumValueDescriptorProtoAminoMsg): _80.EnumValueDescriptorProto;
            fromProtoMsg(message: _80.EnumValueDescriptorProtoProtoMsg): _80.EnumValueDescriptorProto;
            toProto(message: _80.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.EnumValueDescriptorProto): _80.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _80.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.ServiceDescriptorProto;
            fromPartial(object: Partial<_80.ServiceDescriptorProto>): _80.ServiceDescriptorProto;
            fromAmino(object: _80.ServiceDescriptorProtoAmino): _80.ServiceDescriptorProto;
            toAmino(message: _80.ServiceDescriptorProto): _80.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _80.ServiceDescriptorProtoAminoMsg): _80.ServiceDescriptorProto;
            fromProtoMsg(message: _80.ServiceDescriptorProtoProtoMsg): _80.ServiceDescriptorProto;
            toProto(message: _80.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.ServiceDescriptorProto): _80.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _80.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.MethodDescriptorProto;
            fromPartial(object: Partial<_80.MethodDescriptorProto>): _80.MethodDescriptorProto;
            fromAmino(object: _80.MethodDescriptorProtoAmino): _80.MethodDescriptorProto;
            toAmino(message: _80.MethodDescriptorProto): _80.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _80.MethodDescriptorProtoAminoMsg): _80.MethodDescriptorProto;
            fromProtoMsg(message: _80.MethodDescriptorProtoProtoMsg): _80.MethodDescriptorProto;
            toProto(message: _80.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _80.MethodDescriptorProto): _80.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _80.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.FileOptions;
            fromPartial(object: Partial<_80.FileOptions>): _80.FileOptions;
            fromAmino(object: _80.FileOptionsAmino): _80.FileOptions;
            toAmino(message: _80.FileOptions): _80.FileOptionsAmino;
            fromAminoMsg(object: _80.FileOptionsAminoMsg): _80.FileOptions;
            fromProtoMsg(message: _80.FileOptionsProtoMsg): _80.FileOptions;
            toProto(message: _80.FileOptions): Uint8Array;
            toProtoMsg(message: _80.FileOptions): _80.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _80.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.MessageOptions;
            fromPartial(object: Partial<_80.MessageOptions>): _80.MessageOptions;
            fromAmino(object: _80.MessageOptionsAmino): _80.MessageOptions;
            toAmino(message: _80.MessageOptions): _80.MessageOptionsAmino;
            fromAminoMsg(object: _80.MessageOptionsAminoMsg): _80.MessageOptions;
            fromProtoMsg(message: _80.MessageOptionsProtoMsg): _80.MessageOptions;
            toProto(message: _80.MessageOptions): Uint8Array;
            toProtoMsg(message: _80.MessageOptions): _80.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _80.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.FieldOptions;
            fromPartial(object: Partial<_80.FieldOptions>): _80.FieldOptions;
            fromAmino(object: _80.FieldOptionsAmino): _80.FieldOptions;
            toAmino(message: _80.FieldOptions): _80.FieldOptionsAmino;
            fromAminoMsg(object: _80.FieldOptionsAminoMsg): _80.FieldOptions;
            fromProtoMsg(message: _80.FieldOptionsProtoMsg): _80.FieldOptions;
            toProto(message: _80.FieldOptions): Uint8Array;
            toProtoMsg(message: _80.FieldOptions): _80.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _80.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.OneofOptions;
            fromPartial(object: Partial<_80.OneofOptions>): _80.OneofOptions;
            fromAmino(object: _80.OneofOptionsAmino): _80.OneofOptions;
            toAmino(message: _80.OneofOptions): _80.OneofOptionsAmino;
            fromAminoMsg(object: _80.OneofOptionsAminoMsg): _80.OneofOptions;
            fromProtoMsg(message: _80.OneofOptionsProtoMsg): _80.OneofOptions;
            toProto(message: _80.OneofOptions): Uint8Array;
            toProtoMsg(message: _80.OneofOptions): _80.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _80.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.EnumOptions;
            fromPartial(object: Partial<_80.EnumOptions>): _80.EnumOptions;
            fromAmino(object: _80.EnumOptionsAmino): _80.EnumOptions;
            toAmino(message: _80.EnumOptions): _80.EnumOptionsAmino;
            fromAminoMsg(object: _80.EnumOptionsAminoMsg): _80.EnumOptions;
            fromProtoMsg(message: _80.EnumOptionsProtoMsg): _80.EnumOptions;
            toProto(message: _80.EnumOptions): Uint8Array;
            toProtoMsg(message: _80.EnumOptions): _80.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _80.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.EnumValueOptions;
            fromPartial(object: Partial<_80.EnumValueOptions>): _80.EnumValueOptions;
            fromAmino(object: _80.EnumValueOptionsAmino): _80.EnumValueOptions;
            toAmino(message: _80.EnumValueOptions): _80.EnumValueOptionsAmino;
            fromAminoMsg(object: _80.EnumValueOptionsAminoMsg): _80.EnumValueOptions;
            fromProtoMsg(message: _80.EnumValueOptionsProtoMsg): _80.EnumValueOptions;
            toProto(message: _80.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _80.EnumValueOptions): _80.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _80.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.ServiceOptions;
            fromPartial(object: Partial<_80.ServiceOptions>): _80.ServiceOptions;
            fromAmino(object: _80.ServiceOptionsAmino): _80.ServiceOptions;
            toAmino(message: _80.ServiceOptions): _80.ServiceOptionsAmino;
            fromAminoMsg(object: _80.ServiceOptionsAminoMsg): _80.ServiceOptions;
            fromProtoMsg(message: _80.ServiceOptionsProtoMsg): _80.ServiceOptions;
            toProto(message: _80.ServiceOptions): Uint8Array;
            toProtoMsg(message: _80.ServiceOptions): _80.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _80.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.MethodOptions;
            fromPartial(object: Partial<_80.MethodOptions>): _80.MethodOptions;
            fromAmino(object: _80.MethodOptionsAmino): _80.MethodOptions;
            toAmino(message: _80.MethodOptions): _80.MethodOptionsAmino;
            fromAminoMsg(object: _80.MethodOptionsAminoMsg): _80.MethodOptions;
            fromProtoMsg(message: _80.MethodOptionsProtoMsg): _80.MethodOptions;
            toProto(message: _80.MethodOptions): Uint8Array;
            toProtoMsg(message: _80.MethodOptions): _80.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _80.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.UninterpretedOption;
            fromPartial(object: Partial<_80.UninterpretedOption>): _80.UninterpretedOption;
            fromAmino(object: _80.UninterpretedOptionAmino): _80.UninterpretedOption;
            toAmino(message: _80.UninterpretedOption): _80.UninterpretedOptionAmino;
            fromAminoMsg(object: _80.UninterpretedOptionAminoMsg): _80.UninterpretedOption;
            fromProtoMsg(message: _80.UninterpretedOptionProtoMsg): _80.UninterpretedOption;
            toProto(message: _80.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _80.UninterpretedOption): _80.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _80.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_80.UninterpretedOption_NamePart>): _80.UninterpretedOption_NamePart;
            fromAmino(object: _80.UninterpretedOption_NamePartAmino): _80.UninterpretedOption_NamePart;
            toAmino(message: _80.UninterpretedOption_NamePart): _80.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _80.UninterpretedOption_NamePartAminoMsg): _80.UninterpretedOption_NamePart;
            fromProtoMsg(message: _80.UninterpretedOption_NamePartProtoMsg): _80.UninterpretedOption_NamePart;
            toProto(message: _80.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _80.UninterpretedOption_NamePart): _80.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _80.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.SourceCodeInfo;
            fromPartial(object: Partial<_80.SourceCodeInfo>): _80.SourceCodeInfo;
            fromAmino(object: _80.SourceCodeInfoAmino): _80.SourceCodeInfo;
            toAmino(message: _80.SourceCodeInfo): _80.SourceCodeInfoAmino;
            fromAminoMsg(object: _80.SourceCodeInfoAminoMsg): _80.SourceCodeInfo;
            fromProtoMsg(message: _80.SourceCodeInfoProtoMsg): _80.SourceCodeInfo;
            toProto(message: _80.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _80.SourceCodeInfo): _80.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _80.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.SourceCodeInfo_Location;
            fromPartial(object: Partial<_80.SourceCodeInfo_Location>): _80.SourceCodeInfo_Location;
            fromAmino(object: _80.SourceCodeInfo_LocationAmino): _80.SourceCodeInfo_Location;
            toAmino(message: _80.SourceCodeInfo_Location): _80.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _80.SourceCodeInfo_LocationAminoMsg): _80.SourceCodeInfo_Location;
            fromProtoMsg(message: _80.SourceCodeInfo_LocationProtoMsg): _80.SourceCodeInfo_Location;
            toProto(message: _80.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _80.SourceCodeInfo_Location): _80.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _80.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.GeneratedCodeInfo;
            fromPartial(object: Partial<_80.GeneratedCodeInfo>): _80.GeneratedCodeInfo;
            fromAmino(object: _80.GeneratedCodeInfoAmino): _80.GeneratedCodeInfo;
            toAmino(message: _80.GeneratedCodeInfo): _80.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _80.GeneratedCodeInfoAminoMsg): _80.GeneratedCodeInfo;
            fromProtoMsg(message: _80.GeneratedCodeInfoProtoMsg): _80.GeneratedCodeInfo;
            toProto(message: _80.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _80.GeneratedCodeInfo): _80.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _80.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _80.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_80.GeneratedCodeInfo_Annotation>): _80.GeneratedCodeInfo_Annotation;
            fromAmino(object: _80.GeneratedCodeInfo_AnnotationAmino): _80.GeneratedCodeInfo_Annotation;
            toAmino(message: _80.GeneratedCodeInfo_Annotation): _80.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _80.GeneratedCodeInfo_AnnotationAminoMsg): _80.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _80.GeneratedCodeInfo_AnnotationProtoMsg): _80.GeneratedCodeInfo_Annotation;
            toProto(message: _80.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _80.GeneratedCodeInfo_Annotation): _80.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
